/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "./utils";
import {
  Button,
  Icon,
  Image,
  SearchField,
  Text,
  View,
} from "@aws-amplify/ui-react";
export default function Comunidade(props) {
  const { overrides, ...rest } = props;
  return (
    <View
      width="1514px"
      height="1879px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      position="relative"
      padding="0px 0px 0px 0px"
      {...getOverrideProps(overrides, "Comunidade")}
      {...rest}
    >
      <Image
        width="100%"
        height="100%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="0%"
        bottom="0%"
        left="0%"
        right="0%"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "Fundo Novo")}
      ></Image>
      <SearchField
        width="690px"
        height="unset"
        placeholder="Faça uma pesquisa incrível"
        position="absolute"
        top="8.2%"
        bottom="89.36%"
        left="23.32%"
        right="31.11%"
        size="large"
        isDisabled={true}
        labelHidden={true}
        variation="default"
        {...getOverrideProps(overrides, "SearchField")}
      ></SearchField>
      <View
        width="24px"
        height="24px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        overflow="hidden"
        position="absolute"
        top="16.13%"
        bottom="82.6%"
        left="34.87%"
        right="63.54%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(
          overrides,
          "search_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24 1"
        )}
      ></View>
      <View
        padding="0px 0px 0px 0px"
        width="301px"
        height="377px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="8.2%"
        bottom="71.74%"
        left="1.72%"
        right="78.4%"
        {...getOverrideProps(overrides, "Group 488")}
      >
        <View
          width="301px"
          height="377px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0%"
          bottom="0%"
          left="0%"
          right="0%"
          border="1px SOLID rgba(0,0,0,1)"
          boxShadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
          borderRadius="8px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(255,255,255,1)"
          {...getOverrideProps(overrides, "Rectangle 12239013388")}
        ></View>
        <Image
          width="53.16%"
          height="42.44%"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="9.81%"
          bottom="47.75%"
          left="23.26%"
          right="23.59%"
          border="1px SOLID rgba(0,0,0,1)"
          borderRadius="300px"
          padding="0px 0px 0px 0px"
          objectFit="cover"
          {...getOverrideProps(overrides, "image39013389")}
        ></Image>
        <Text
          fontFamily="Montserrat"
          fontSize="24px"
          fontWeight="600"
          color="rgba(0,0,0,1)"
          lineHeight="29.256000518798828px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          width="174px"
          height="23px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="59.42%"
          bottom="34.48%"
          left="21.26%"
          right="20.93%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Novo Usuário"
          {...getOverrideProps(overrides, "Novo Usu\u00E1rio")}
        ></Text>
      </View>
      <View
        width="35px"
        height="34.01px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="34.46%"
        bottom="63.73%"
        left="34.02%"
        right="63.67%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Male User")}
      ></View>
      <View
        width="685px"
        height="421px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="72.11%"
        bottom="5.48%"
        left="23.32%"
        right="31.44%"
        border="1px SOLID rgba(0,0,0,0.4)"
        borderRadius="10px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(255,255,255,0.6)"
        {...getOverrideProps(overrides, "Rectangle 143")}
      ></View>
      <View
        width="691px"
        height="527px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="42.79%"
        bottom="29.16%"
        left="23.32%"
        right="31.04%"
        border="1px SOLID rgba(0,0,0,0.4)"
        borderRadius="10px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(255,255,255,0.6)"
        {...getOverrideProps(overrides, "Rectangle 140")}
      ></View>
      <View
        width="685px"
        height="485px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="72.11%"
        bottom="2.08%"
        left="23.32%"
        right="31.44%"
        border="1px SOLID rgba(0,0,0,0.4)"
        borderRadius="10px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(255,255,255,0.6)"
        {...getOverrideProps(overrides, "Rectangle 142")}
      ></View>
      <Text
        fontFamily="Montserrat"
        fontSize="20px"
        fontWeight="500"
        color="rgba(0,0,0,1)"
        lineHeight="24.3799991607666px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="566px"
        height="88px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="50.29%"
        bottom="45.02%"
        left="25.1%"
        right="37.52%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Tive a honra de participar do Tech Future Summit 2024, um evento cheio de insights sobre tecnologia e inovação. Foi incrível ... mais"
        {...getOverrideProps(
          overrides,
          "Tive a honra de participar do Tech Future Summit 2024, um evento cheio de insights sobre tecnologia e inova\u00E7\u00E3o. Foi incr\u00EDvel ... mais"
        )}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="20px"
        fontWeight="500"
        color="rgba(0,0,0,1)"
        lineHeight="30px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="642px"
        height="88px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="79.46%"
        bottom="15.86%"
        left="24.83%"
        right="32.76%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Estar no EducaInova 2024 foi uma experiência enriquecedora! Discutir novas metodologias e ferramentas para a educação moderna me trouxe insights valiosos para aplicar ... mais"
        {...getOverrideProps(
          overrides,
          "Estar no EducaInova 2024 foi uma experi\u00EAncia enriquecedora! Discutir novas metodologias e ferramentas para a educa\u00E7\u00E3o moderna me trouxe insights valiosos para aplicar ... mais"
        )}
      ></Text>
      <View
        width="691px"
        height="518px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="14.16%"
        bottom="58.28%"
        left="23.32%"
        right="31.04%"
        border="1px SOLID rgba(0,0,0,0.4)"
        borderRadius="10px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(255,255,255,0.6)"
        {...getOverrideProps(overrides, "Rectangle 141")}
      ></View>
      <Text
        fontFamily="Montserrat"
        fontSize="28px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="34.13199996948242px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="298px"
        height="31px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="16.98%"
        bottom="81.37%"
        left="31.57%"
        right="48.75%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="João Pedro Borges"
        {...getOverrideProps(overrides, "Jo\u00E3o Pedro Borges")}
      ></Text>
      <Text
        fontFamily="Montserrat"
        fontSize="28px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="34.13199996948242px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="327.87px"
        height="31.36px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="45.4%"
        bottom="52.93%"
        left="32.03%"
        right="46.31%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Gabriel Augusto"
        {...getOverrideProps(overrides, "Gabriel Augusto")}
      ></Text>
      <Text
        fontFamily="Montserrat"
        fontSize="28px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="34.13199996948242px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="325px"
        height="32px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="74.72%"
        bottom="23.58%"
        left="32.36%"
        right="46.17%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Aurora Seles"
        {...getOverrideProps(overrides, "Aurora Seles")}
      ></Text>
      <Image
        width="6.08%"
        height="5.16%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="15.38%"
        bottom="79.46%"
        left="24.11%"
        right="69.82%"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "AvatarPerfil 1")}
      ></Image>
      <Image
        width="5.26%"
        height="4.24%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="44.12%"
        bottom="51.64%"
        left="25.36%"
        right="69.37%"
        borderRadius="300px"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "image39013402")}
      ></Image>
      <Image
        width="5.22%"
        height="4.2%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="73.66%"
        bottom="22.14%"
        left="25.43%"
        right="69.35%"
        borderRadius="300px"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "image39013403")}
      ></Image>
      <Text
        fontFamily="Montserrat"
        fontSize="16px"
        fontWeight="500"
        color="rgba(0,0,0,1)"
        lineHeight="19.503999710083008px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="647px"
        height="88px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="21.55%"
        bottom="73.76%"
        left="25.3%"
        right="31.97%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Boa tarde amigos!&#xA;Hoje tive a incrível oportunidade de visitar a sede da CityCorp, e posso dizer que essa experiência foi ...mais"
        {...getOverrideProps(
          overrides,
          "Boa tarde amigos! Hoje tive a incr\u00EDvel oportunidade de visitar a sede da CityCorp, e posso dizer que essa experi\u00EAncia foi ...mais"
        )}
      ></Text>
      <Image
        width="10.63%"
        height="12.67%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="27.62%"
        bottom="59.71%"
        left="25.63%"
        right="63.74%"
        borderRadius="5px"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "image39013405")}
      ></Image>
      <Image
        width="10.63%"
        height="12.67%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="56.87%"
        bottom="30.46%"
        left="24.77%"
        right="64.6%"
        borderRadius="5px"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "image39013406")}
      ></Image>
      <Image
        width="10.5%"
        height="10.38%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="86%"
        bottom="3.62%"
        left="26.68%"
        right="62.81%"
        borderRadius="5px"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "image39013407")}
      ></Image>
      <Image
        width="12.43%"
        height="6.17%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="27.62%"
        bottom="66.2%"
        left="36.95%"
        right="50.62%"
        borderRadius="5px"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "image39013408")}
      ></Image>
      <Image
        width="12.43%"
        height="6.17%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="56.87%"
        bottom="36.95%"
        left="36.09%"
        right="51.48%"
        borderRadius="5px"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "image39013409")}
      ></Image>
      <Image
        width="12.29%"
        height="6.17%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="86%"
        bottom="7.82%"
        left="37.91%"
        right="49.8%"
        borderRadius="5px"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "image39013410")}
      ></Image>
      <Image
        width="12.42%"
        height="5.8%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="27.62%"
        bottom="66.58%"
        left="50.09%"
        right="37.49%"
        borderRadius="5px"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "image39013411")}
      ></Image>
      <Image
        width="12.42%"
        height="5.8%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="56.87%"
        bottom="37.33%"
        left="49.23%"
        right="38.35%"
        borderRadius="5px"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "image39013412")}
      ></Image>
      <Image
        width="12.29%"
        height="5.8%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="86%"
        bottom="8.2%"
        left="50.92%"
        right="36.79%"
        borderRadius="5px"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "image39013413")}
      ></Image>
      <Image
        width="12.43%"
        height="5.97%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="34.27%"
        bottom="59.76%"
        left="36.95%"
        right="50.62%"
        borderRadius="5px"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "image39013414")}
      ></Image>
      <Image
        width="12.43%"
        height="5.97%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="63.52%"
        bottom="30.51%"
        left="36.09%"
        right="51.48%"
        borderRadius="5px"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "image39013415")}
      ></Image>
      <Image
        width="12.42%"
        height="3.73%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="92.66%"
        bottom="3.62%"
        left="37.85%"
        right="49.74%"
        borderRadius="5px"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "image39013416")}
      ></Image>
      <Image
        width="12.43%"
        height="5.97%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="34.38%"
        bottom="59.65%"
        left="50.09%"
        right="37.48%"
        borderRadius="5px"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "image39013417")}
      ></Image>
      <Image
        width="12.43%"
        height="5.97%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="63.63%"
        bottom="30.4%"
        left="49.23%"
        right="38.33%"
        borderRadius="5px"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "image39013418")}
      ></Image>
      <Image
        width="12.35%"
        height="3.73%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="92.66%"
        bottom="3.62%"
        left="50.92%"
        right="36.72%"
        borderRadius="5px"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "image39013419")}
      ></Image>
      <Text
        fontFamily="Montserrat"
        fontSize="40px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="48.7599983215332px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="36.14%"
        bottom="61.25%"
        left="53.24%"
        right="42.6%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="+ 4"
        {...getOverrideProps(overrides, "+ 4")}
      ></Text>
      <Text
        fontFamily="Montserrat"
        fontSize="40px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="48.7599983215332px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="65.39%"
        bottom="32%"
        left="53.17%"
        right="42.93%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="+ 3"
        {...getOverrideProps(overrides, "+ 3")}
      ></Text>
      <Text
        fontFamily="Montserrat"
        fontSize="24px"
        fontWeight="700"
        color="rgba(255,255,255,1)"
        lineHeight="29.256000518798828px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="58px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="93.93%"
        bottom="4.52%"
        left="55.55%"
        right="40.62%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="+ 7"
        {...getOverrideProps(overrides, "+ 7")}
      ></Text>
      <Text
        fontFamily="Montserrat"
        fontSize="15px"
        fontWeight="300"
        color="rgba(0,0,0,1)"
        lineHeight="18.28499984741211px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="84.54px"
        height="18.81px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="15.86%"
        bottom="83.14%"
        left="63.28%"
        right="31.14%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="4 min"
        {...getOverrideProps(overrides, "4 min")}
      ></Text>
      <Text
        fontFamily="Montserrat"
        fontSize="15px"
        fontWeight="300"
        color="rgba(0,0,0,1)"
        lineHeight="18.28499984741211px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="37px"
        height="19px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="44.49%"
        bottom="54.5%"
        left="64.6%"
        right="32.96%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="5 h"
        {...getOverrideProps(overrides, "5 h")}
      ></Text>
      <Text
        fontFamily="Montserrat"
        fontSize="15px"
        fontWeight="300"
        color="rgba(0,0,0,1)"
        lineHeight="18.28499984741211px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="84px"
        height="19px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="73.66%"
        bottom="25.33%"
        left="64.66%"
        right="29.79%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="5 d"
        {...getOverrideProps(overrides, "5 d")}
      ></Text>
      <View
        width="430px"
        height="287px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="8.2%"
        bottom="76.53%"
        left="71%"
        right="0.59%"
        border="1px SOLID rgba(0,0,0,1)"
        boxShadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
        borderRadius="8px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(255,255,255,1)"
        {...getOverrideProps(overrides, "Rectangle 12239013426")}
      ></View>
      <Image
        width="8.59%"
        height="6.97%"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="10.8%"
        bottom="82.22%"
        left="73.84%"
        right="17.57%"
        borderRadius="300px"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "image39013427")}
      ></Image>
      <Text
        fontFamily="Montserrat"
        fontSize="24px"
        fontWeight="600"
        color="rgba(0,0,0,1)"
        lineHeight="29.256000518798828px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="283px"
        height="24px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="19.64%"
        bottom="79.08%"
        left="73.84%"
        right="7.46%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Lucas Silva Rodrigues"
        {...getOverrideProps(overrides, "Lucas Silva Rodrigues")}
      ></Text>
      <Text
        fontFamily="Montserrat"
        fontSize="14px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="17.06599998474121px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="242px"
        height="47px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="14.05%"
        bottom="83.45%"
        left="84.02%"
        right="0%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="“Meu sonho é ser um médico conhecido um dia !”"
        {...getOverrideProps(
          overrides,
          "\u201CMeu sonho \u00E9 ser um m\u00E9dico conhecido um dia !\u201D"
        )}
      ></Text>
      <Text
        fontFamily="Montserrat"
        fontSize="15px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="18.28499984741211px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="86px"
        height="24px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="10.06%"
        bottom="88.66%"
        left="92.54%"
        right="1.78%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Sugestão"
        {...getOverrideProps(overrides, "Sugest\u00E3o")}
      ></Text>
      <View
        padding="0px 0px 0px 0px"
        width="430px"
        height="298px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="24.11%"
        bottom="60.03%"
        left="71.07%"
        right="0.53%"
        {...getOverrideProps(overrides, "Group 490")}
      >
        <View
          width="430px"
          height="298px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0%"
          bottom="0%"
          left="0%"
          right="0%"
          border="1px SOLID rgba(0,0,0,1)"
          boxShadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
          borderRadius="8px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(255,255,255,1)"
          {...getOverrideProps(overrides, "Rectangle 12239013432")}
        ></View>
        <Image
          width="30.47%"
          height="43.96%"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="12.75%"
          bottom="43.29%"
          left="34.88%"
          right="34.65%"
          border="1px SOLID rgba(0,0,0,1)"
          borderRadius="300px"
          padding="0px 0px 0px 0px"
          objectFit="cover"
          {...getOverrideProps(overrides, "image39013433")}
        ></Image>
        <Text
          fontFamily="Montserrat"
          fontSize="24px"
          fontWeight="600"
          color="rgba(0,0,0,1)"
          lineHeight="29.256000518798828px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          width="96px"
          height="24px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="65.77%"
          bottom="26.17%"
          left="38.84%"
          right="38.84%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Evoflui"
          {...getOverrideProps(overrides, "Evoflui")}
        ></Text>
        <Text
          fontFamily="Montserrat"
          fontSize="16px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="19.503999710083008px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          width="342px"
          height="24px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="81.21%"
          bottom="10.74%"
          left="11.63%"
          right="8.84%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Seja único, Seja você mesmo, Seja Evoflui."
          {...getOverrideProps(
            overrides,
            "Seja \u00FAnico, Seja voc\u00EA mesmo, Seja Evoflui."
          )}
        ></Text>
        <Text
          fontFamily="Montserrat"
          fontSize="15px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="18.28499984741211px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="69.49px"
          height="24px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="11.74%"
          bottom="80.2%"
          left="81.01%"
          right="2.83%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Parceria"
          {...getOverrideProps(overrides, "Parceria")}
        ></Text>
      </View>
      <View
        padding="0px 0px 0px 0px"
        width="301px"
        height="214px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="28.9%"
        bottom="59.71%"
        left="1.72%"
        right="78.4%"
        {...getOverrideProps(overrides, "Group 491")}
      >
        <View
          width="301px"
          height="214px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0%"
          bottom="0%"
          left="0%"
          right="0%"
          border="1px SOLID rgba(0,0,0,1)"
          boxShadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
          borderRadius="8px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(255,255,255,1)"
          {...getOverrideProps(overrides, "Rectangle 12239013438")}
        ></View>
        <Icon
          width="20px"
          height="20px"
          viewBox={{ minX: 0, minY: 0, width: 20, height: 20 }}
          paths={[
            {
              d: "M10 16.0737L16.18 20L14.54 12.6L20 7.62105L12.81 6.97895L10 0L7.19 6.97895L0 7.62105L5.46 12.6L3.82 20L10 16.0737Z",
              fill: "rgba(191,191,64,1)",
              fillRule: "nonzero",
            },
          ]}
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="77.57%"
          bottom="13.08%"
          left="57.48%"
          right="35.88%"
          {...getOverrideProps(overrides, "Vector")}
        ></Icon>
        <Text
          fontFamily="Poppins"
          fontSize="14px"
          fontWeight="600"
          color="rgba(0,0,0,1)"
          lineHeight="21px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="166px"
          height="33px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="44.86%"
          bottom="39.72%"
          left="44.52%"
          right="0.33%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="ANALISTA DE DADOS"
          {...getOverrideProps(overrides, "ANALISTA DE DADOS")}
        ></Text>
        <Image
          width="29.57%"
          height="30.37%"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="36.45%"
          bottom="33.18%"
          left="9.97%"
          right="60.47%"
          border="1px SOLID rgba(0,0,0,1)"
          borderRadius="20px"
          padding="0px 0px 0px 0px"
          objectFit="cover"
          {...getOverrideProps(overrides, "image 7")}
        ></Image>
        <Text
          fontFamily="Montserrat"
          fontSize="14px"
          fontWeight="700"
          color="rgba(0,0,0,1)"
          lineHeight="17.06599998474121px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="34px"
          height="19px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="77.57%"
          bottom="13.55%"
          left="9.97%"
          right="78.74%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="4,5"
          {...getOverrideProps(overrides, "4,5")}
        ></Text>
        <Text
          fontFamily="Montserrat"
          fontSize="15px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="18.28499984741211px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="130px"
          height="20px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="15.89%"
          bottom="74.77%"
          left="9.97%"
          right="46.84%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Recomendações"
          {...getOverrideProps(overrides, "Recomenda\u00E7\u00F5es")}
        ></Text>
        <Text
          fontFamily="Montserrat"
          fontSize="16px"
          fontWeight="700"
          color="rgba(0,148,255,1)"
          lineHeight="19.503999710083008px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="117px"
          height="20px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="77.57%"
          bottom="13.08%"
          left="22.59%"
          right="38.54%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="REKTR TEC"
          {...getOverrideProps(overrides, "REKTR TEC")}
        ></Text>
      </View>
      <Button
        width="137px"
        height="unset"
        position="absolute"
        top="23.36%"
        bottom="74.51%"
        left="6.94%"
        right="84.02%"
        backgroundColor="rgba(191,128,64,1)"
        size="default"
        isDisabled={false}
        variation="primary"
        children="Criar Conta"
        {...getOverrideProps(overrides, "Button39013445")}
      ></Button>
      <View
        width="24px"
        height="24px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        overflow="hidden"
        position="absolute"
        top="67.48%"
        bottom="31.24%"
        left="6.67%"
        right="91.74%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(
          overrides,
          "forward_to_inbox_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 1"
        )}
      ></View>
      <View
        padding="0px 0px 0px 0px"
        width="1518px"
        height="70px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="0%"
        bottom="96.27%"
        left="0%"
        right="-0.26%"
        {...getOverrideProps(overrides, "NavHeader")}
      >
        <View
          width="1518px"
          height="70px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0%"
          bottom="0%"
          left="0%"
          right="0%"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(15,45,57,1)"
          {...getOverrideProps(overrides, "Rectangle 206")}
        ></View>
        <Button
          width="155.2px"
          height="33px"
          position="absolute"
          border="1px SOLID rgba(255,255,255,1)"
          top="34.29%"
          bottom="18.57%"
          left="87.4%"
          right="2.37%"
          backgroundColor="rgba(0,0,0,0)"
          size="default"
          isDisabled={false}
          variation="primary"
          children="Cadastrar-se"
          {...getOverrideProps(overrides, "Button39013774")}
        ></Button>
        <Image
          width="12.01%"
          height="34.29%"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="38.57%"
          bottom="27.14%"
          left="2.44%"
          right="85.55%"
          padding="0px 0px 0px 0px"
          objectFit="cover"
          {...getOverrideProps(overrides, "logo_branca_conecta 2")}
        ></Image>
        <Button
          width="65.09px"
          height="unset"
          position="absolute"
          top="calc(50% - 16.5px - -3.5px)"
          left="19.92%"
          right="75.79%"
          backgroundColor="rgba(0,0,0,0)"
          size="small"
          isDisabled={false}
          variation="primary"
          children="Home"
          {...getOverrideProps(overrides, "Button39013776")}
        ></Button>
        <Button
          width="61.08px"
          height="unset"
          position="absolute"
          top="calc(50% - 16.5px - -3.5px)"
          left="47.56%"
          right="48.42%"
          backgroundColor="rgba(0,0,0,0)"
          size="small"
          isDisabled={false}
          variation="primary"
          children="Comunidade"
          {...getOverrideProps(overrides, "Button39013777")}
        ></Button>
        <Button
          width="125.16px"
          height="unset"
          position="absolute"
          top="calc(50% - 16.5px - -3.5px)"
          left="31.53%"
          right="60.22%"
          backgroundColor="rgba(0,0,0,0)"
          size="small"
          isDisabled={false}
          variation="primary"
          children="Acessibilidade"
          {...getOverrideProps(overrides, "Button39013778")}
        ></Button>
        <Button
          width="65.09px"
          height="unset"
          position="absolute"
          top="calc(50% - 16.5px - -3.5px)"
          left="61.81%"
          right="33.91%"
          backgroundColor="rgba(0,0,0,0)"
          size="small"
          isDisabled={false}
          variation="primary"
          children="Ajuda"
          {...getOverrideProps(overrides, "Button39013779")}
        ></Button>
        <Button
          width="130.17px"
          height="unset"
          position="absolute"
          top="calc(50% - 16.5px - -5.5px)"
          left="74.41%"
          right="17.02%"
          backgroundColor="rgba(191,128,64,1)"
          size="small"
          isDisabled={false}
          variation="primary"
          children="Entrar"
          {...getOverrideProps(overrides, "Button39013780")}
        ></Button>
      </View>
    </View>
  );
}
