/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { ButtonProps, IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type Home2OverridesProps = {
    Home2?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 26"?: PrimitiveOverrideProps<ViewProps>;
    "foto 1"?: PrimitiveOverrideProps<ViewProps>;
    "Group 68"?: PrimitiveOverrideProps<ViewProps>;
    "Group 381"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 140"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 19"?: PrimitiveOverrideProps<ViewProps>;
    "logo_branca_conecta 1"?: PrimitiveOverrideProps<ImageProps>;
    Vector41002405?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 139"?: PrimitiveOverrideProps<ViewProps>;
    Entrar?: PrimitiveOverrideProps<TextProps>;
    Ajuda?: PrimitiveOverrideProps<TextProps>;
    Vector4008779?: PrimitiveOverrideProps<IconProps>;
    Vector4008783?: PrimitiveOverrideProps<IconProps>;
    Alarm?: PrimitiveOverrideProps<ImageProps>;
    "Cadastrar-se"?: PrimitiveOverrideProps<TextProps>;
    "Conecte-se com oportunidades que valorizam suas habilidades"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 184"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 20"?: PrimitiveOverrideProps<ViewProps>;
    Button40981950?: PrimitiveOverrideProps<ButtonProps>;
    Button40981951?: PrimitiveOverrideProps<ButtonProps>;
    Button40981952?: PrimitiveOverrideProps<ButtonProps>;
    Button39883964?: PrimitiveOverrideProps<ButtonProps>;
    "Line 47"?: PrimitiveOverrideProps<IconProps>;
    "Line 48"?: PrimitiveOverrideProps<IconProps>;
    "SearchIcon 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39883968?: PrimitiveOverrideProps<IconProps>;
    "Cargo | Habilidade"?: PrimitiveOverrideProps<TextProps>;
    "Cidade | Estado"?: PrimitiveOverrideProps<TextProps>;
    "Todas categorias"?: PrimitiveOverrideProps<TextProps>;
    Vector39883972?: PrimitiveOverrideProps<IconProps>;
    Vector39883973?: PrimitiveOverrideProps<IconProps>;
    Vector39883974?: PrimitiveOverrideProps<IconProps>;
    "+39883975"?: PrimitiveOverrideProps<TextProps>;
    "+39883976"?: PrimitiveOverrideProps<TextProps>;
    "+39883977"?: PrimitiveOverrideProps<TextProps>;
    "+39883978"?: PrimitiveOverrideProps<TextProps>;
    "Group 400"?: PrimitiveOverrideProps<ViewProps>;
    "undraw_website_5bo8 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39883981?: PrimitiveOverrideProps<IconProps>;
    Vector39883982?: PrimitiveOverrideProps<IconProps>;
    Vector39883983?: PrimitiveOverrideProps<IconProps>;
    Vector39883984?: PrimitiveOverrideProps<IconProps>;
    Vector39883985?: PrimitiveOverrideProps<IconProps>;
    Vector39883986?: PrimitiveOverrideProps<IconProps>;
    Vector39883987?: PrimitiveOverrideProps<IconProps>;
    Vector39883988?: PrimitiveOverrideProps<IconProps>;
    Vector39883989?: PrimitiveOverrideProps<IconProps>;
    Vector39883990?: PrimitiveOverrideProps<IconProps>;
    "logo_branca_conecta 4"?: PrimitiveOverrideProps<ImageProps>;
    Vector39883992?: PrimitiveOverrideProps<IconProps>;
    Vector39883993?: PrimitiveOverrideProps<IconProps>;
    Vector39883994?: PrimitiveOverrideProps<IconProps>;
    Vector39883995?: PrimitiveOverrideProps<IconProps>;
    Vector39883996?: PrimitiveOverrideProps<IconProps>;
    Vector39883997?: PrimitiveOverrideProps<IconProps>;
    Vector39883998?: PrimitiveOverrideProps<IconProps>;
    Vector39883999?: PrimitiveOverrideProps<IconProps>;
    Vector39884000?: PrimitiveOverrideProps<IconProps>;
    Vector39884001?: PrimitiveOverrideProps<IconProps>;
    Vector39884002?: PrimitiveOverrideProps<IconProps>;
    Vector39884003?: PrimitiveOverrideProps<IconProps>;
    "Sobre n\u00F3s"?: PrimitiveOverrideProps<TextProps>;
    "Sabemos que pessoas com TEA possuem certas limita\u00E7\u00F5es, como a necessidade de interfaces mais simples e menos sobrecarregadas de informa\u00E7\u00E3o. Assim, criamos a Conecta+, uma plataforma que conecta empregadores e candidatos com TEA, promovendo a inclus\u00E3o no mercado de trabalho."?: PrimitiveOverrideProps<TextProps>;
    "Categorias de vagas:"?: PrimitiveOverrideProps<TextProps>;
    "ArrowRightIcon 139884007"?: PrimitiveOverrideProps<ViewProps>;
    Vector39884008?: PrimitiveOverrideProps<IconProps>;
    "Group 428"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 9439884010"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 96"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 9439884012"?: PrimitiveOverrideProps<ViewProps>;
    image39884013?: PrimitiveOverrideProps<ViewProps>;
    image39884014?: PrimitiveOverrideProps<ViewProps>;
    "Sa\u00FAde"?: PrimitiveOverrideProps<TextProps>;
    Tecnologia?: PrimitiveOverrideProps<TextProps>;
    Design?: PrimitiveOverrideProps<TextProps>;
    Vector39884018?: PrimitiveOverrideProps<IconProps>;
    Vector39884019?: PrimitiveOverrideProps<IconProps>;
    Vector39884020?: PrimitiveOverrideProps<IconProps>;
    "chevron_right_24dp_E8EAED_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39884036?: PrimitiveOverrideProps<IconProps>;
    "ArrowRightIcon 139884037"?: PrimitiveOverrideProps<ViewProps>;
    Vector39884038?: PrimitiveOverrideProps<IconProps>;
    "Group 70"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 29"?: PrimitiveOverrideProps<ViewProps>;
    Temas?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 30"?: PrimitiveOverrideProps<ViewProps>;
    "Seguir tema do sistema operacional39884043"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 33"?: PrimitiveOverrideProps<ViewProps>;
    "Seguir tema do sistema operacional39884045"?: PrimitiveOverrideProps<TextProps>;
    Done?: PrimitiveOverrideProps<ImageProps>;
    "Line 18"?: PrimitiveOverrideProps<IconProps>;
    "Alto Contraste"?: PrimitiveOverrideProps<TextProps>;
    Escuro?: PrimitiveOverrideProps<TextProps>;
    Claro?: PrimitiveOverrideProps<TextProps>;
    "ThemeIcon 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector40421145?: PrimitiveOverrideProps<IconProps>;
} & EscapeHatchProps;
export declare type Home2Props = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: Home2OverridesProps | undefined | null;
}>;
export default function Home2(props: Home2Props): React.ReactElement;
