/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { BancoImagens } from "../models";
import { ButtonProps, IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type Home5OverridesProps = {
    Home5?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 26"?: PrimitiveOverrideProps<ViewProps>;
    "foto 1"?: PrimitiveOverrideProps<ViewProps>;
    "Conecte-se com oportunidades que valorizam suas habilidades"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 184"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 185"?: PrimitiveOverrideProps<ViewProps>;
    Buscar?: PrimitiveOverrideProps<TextProps>;
    "Line 47"?: PrimitiveOverrideProps<IconProps>;
    "Line 48"?: PrimitiveOverrideProps<IconProps>;
    "SearchIcon 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector40981791?: PrimitiveOverrideProps<IconProps>;
    "Cargo | Habilidade"?: PrimitiveOverrideProps<TextProps>;
    "Cidade | Estado"?: PrimitiveOverrideProps<TextProps>;
    "Todas categorias"?: PrimitiveOverrideProps<TextProps>;
    Location?: PrimitiveOverrideProps<ImageProps>;
    Shortlist?: PrimitiveOverrideProps<ImageProps>;
    "More Than"?: PrimitiveOverrideProps<ImageProps>;
    "+39886852"?: PrimitiveOverrideProps<TextProps>;
    "+39886853"?: PrimitiveOverrideProps<TextProps>;
    "+39886854"?: PrimitiveOverrideProps<TextProps>;
    "+39886855"?: PrimitiveOverrideProps<TextProps>;
    "Categorias de vagas:"?: PrimitiveOverrideProps<TextProps>;
    "Suas ultimas vagas"?: PrimitiveOverrideProps<TextProps>;
    "Group 87"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 9439886859"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 96"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 9439886861"?: PrimitiveOverrideProps<ViewProps>;
    image39886862?: PrimitiveOverrideProps<ViewProps>;
    image39886863?: PrimitiveOverrideProps<ViewProps>;
    "Sa\u00FAde"?: PrimitiveOverrideProps<TextProps>;
    Tecnologia?: PrimitiveOverrideProps<TextProps>;
    "image-removebg-preview (5) 1"?: PrimitiveOverrideProps<ImageProps>;
    "image 19"?: PrimitiveOverrideProps<ImageProps>;
    Vector40981793?: PrimitiveOverrideProps<IconProps>;
    Design?: PrimitiveOverrideProps<TextProps>;
    "chevron_backward_24dp_5F6368_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector40981796?: PrimitiveOverrideProps<IconProps>;
    "Group 423"?: PrimitiveOverrideProps<ViewProps>;
    "Group 68"?: PrimitiveOverrideProps<ViewProps>;
    "Group 381"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 19"?: PrimitiveOverrideProps<ViewProps>;
    "logo_branca_conecta 1"?: PrimitiveOverrideProps<ImageProps>;
    Vector40901332?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 139"?: PrimitiveOverrideProps<IconProps>;
    Help?: PrimitiveOverrideProps<ViewProps>;
    Vector39886879?: PrimitiveOverrideProps<IconProps>;
    Ajuda?: PrimitiveOverrideProps<TextProps>;
    "Jo\u00E3o Pedro Borges"?: PrimitiveOverrideProps<TextProps>;
    Vector39886884?: PrimitiveOverrideProps<IconProps>;
    "Line 49"?: PrimitiveOverrideProps<IconProps>;
    "Line 51"?: PrimitiveOverrideProps<IconProps>;
    "Group 40139886887"?: PrimitiveOverrideProps<ViewProps>;
    "Group 40140981773"?: PrimitiveOverrideProps<ViewProps>;
    "Group 399"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 152"?: PrimitiveOverrideProps<IconProps>;
    "1.783 avalia\u00E7\u00F5es"?: PrimitiveOverrideProps<TextProps>;
    "S\u00E3o Paulo - SP"?: PrimitiveOverrideProps<TextProps>;
    "R$ 5.200,00"?: PrimitiveOverrideProps<TextProps>;
    "H\u00EDbrido"?: PrimitiveOverrideProps<TextProps>;
    "ANALISTA DE DADOS"?: PrimitiveOverrideProps<TextProps>;
    "image 7"?: PrimitiveOverrideProps<ImageProps>;
    "4,5"?: PrimitiveOverrideProps<TextProps>;
    "star_24dp_000000_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector40981784?: PrimitiveOverrideProps<IconProps>;
    "REKTR TEC"?: PrimitiveOverrideProps<TextProps>;
    "new_releases_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector40981787?: PrimitiveOverrideProps<IconProps>;
    Vector40981788?: PrimitiveOverrideProps<IconProps>;
    "undraw_profile_re_4a55 1"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 62"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 75"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 80"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 90"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 91"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 92"?: PrimitiveOverrideProps<IconProps>;
    "Path 14239886913"?: PrimitiveOverrideProps<IconProps>;
    "Path 14339886914"?: PrimitiveOverrideProps<IconProps>;
    "Path 14239886915"?: PrimitiveOverrideProps<IconProps>;
    "Path 14339886916"?: PrimitiveOverrideProps<IconProps>;
    "Path 14239886917"?: PrimitiveOverrideProps<IconProps>;
    "Path 14339886918"?: PrimitiveOverrideProps<IconProps>;
    Vector39886919?: PrimitiveOverrideProps<IconProps>;
    Vector39886920?: PrimitiveOverrideProps<IconProps>;
    Vector39886921?: PrimitiveOverrideProps<IconProps>;
    Vector39886922?: PrimitiveOverrideProps<IconProps>;
    Vector39886923?: PrimitiveOverrideProps<IconProps>;
    Vector39886924?: PrimitiveOverrideProps<IconProps>;
    "Frame 9"?: PrimitiveOverrideProps<ViewProps>;
    Vector39886926?: PrimitiveOverrideProps<IconProps>;
    Vector39886927?: PrimitiveOverrideProps<IconProps>;
    Vector39886928?: PrimitiveOverrideProps<IconProps>;
    Vector39886929?: PrimitiveOverrideProps<IconProps>;
    Vector39886930?: PrimitiveOverrideProps<IconProps>;
    Vector39886931?: PrimitiveOverrideProps<IconProps>;
    Vector39886932?: PrimitiveOverrideProps<IconProps>;
    Vector39886933?: PrimitiveOverrideProps<IconProps>;
    Vector39886934?: PrimitiveOverrideProps<IconProps>;
    Vector39886935?: PrimitiveOverrideProps<IconProps>;
    Vector39886936?: PrimitiveOverrideProps<IconProps>;
    Vector39886937?: PrimitiveOverrideProps<IconProps>;
    Vector39886938?: PrimitiveOverrideProps<IconProps>;
    Vector39886939?: PrimitiveOverrideProps<IconProps>;
    Vector39886940?: PrimitiveOverrideProps<IconProps>;
    "robot-modern-flat-style-vector-removebg-preview 1"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 188"?: PrimitiveOverrideProps<ViewProps>;
    "Ol\u00E1, como posso te ajudar hoje ?"?: PrimitiveOverrideProps<TextProps>;
    "D\u00DAVIDAS FREQUENTES"?: PrimitiveOverrideProps<TextProps>;
    Monica?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 189"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 190"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 191"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 192"?: PrimitiveOverrideProps<ViewProps>;
    "Digite sua d\u00FAvida..."?: PrimitiveOverrideProps<TextProps>;
    "Cadastro e Perfil"?: PrimitiveOverrideProps<TextProps>;
    "Aplica\u00E7\u00E3o a Vagas"?: PrimitiveOverrideProps<TextProps>;
    "Comunica\u00E7\u00E3o e Servi\u00E7os"?: PrimitiveOverrideProps<TextProps>;
    "Line 54"?: PrimitiveOverrideProps<IconProps>;
    "undraw_chat_bot_re_e2gj 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39886957?: PrimitiveOverrideProps<IconProps>;
    Vector39886958?: PrimitiveOverrideProps<IconProps>;
    Vector39886959?: PrimitiveOverrideProps<IconProps>;
    Vector39886960?: PrimitiveOverrideProps<IconProps>;
    Vector39886961?: PrimitiveOverrideProps<IconProps>;
    Vector39886962?: PrimitiveOverrideProps<IconProps>;
    Vector39886963?: PrimitiveOverrideProps<IconProps>;
    Vector39886964?: PrimitiveOverrideProps<IconProps>;
    Vector39886965?: PrimitiveOverrideProps<IconProps>;
    Vector39886966?: PrimitiveOverrideProps<IconProps>;
    Vector39886967?: PrimitiveOverrideProps<IconProps>;
    Vector39886968?: PrimitiveOverrideProps<IconProps>;
    Vector39886969?: PrimitiveOverrideProps<IconProps>;
    Vector39886970?: PrimitiveOverrideProps<IconProps>;
    Vector39886971?: PrimitiveOverrideProps<IconProps>;
    Vector39886972?: PrimitiveOverrideProps<IconProps>;
    Vector39886973?: PrimitiveOverrideProps<IconProps>;
    Vector39886974?: PrimitiveOverrideProps<IconProps>;
    Vector39886975?: PrimitiveOverrideProps<IconProps>;
    Vector39886976?: PrimitiveOverrideProps<IconProps>;
    Vector39886977?: PrimitiveOverrideProps<IconProps>;
    Vector39886978?: PrimitiveOverrideProps<IconProps>;
    Vector39886979?: PrimitiveOverrideProps<IconProps>;
    Vector39886980?: PrimitiveOverrideProps<IconProps>;
    Vector39886981?: PrimitiveOverrideProps<IconProps>;
    Vector39886982?: PrimitiveOverrideProps<IconProps>;
    Vector39886983?: PrimitiveOverrideProps<IconProps>;
    Vector39886984?: PrimitiveOverrideProps<IconProps>;
    Vector39886985?: PrimitiveOverrideProps<IconProps>;
    Vector39886986?: PrimitiveOverrideProps<IconProps>;
    Vector39886987?: PrimitiveOverrideProps<IconProps>;
    Vector39886988?: PrimitiveOverrideProps<IconProps>;
    Vector39886989?: PrimitiveOverrideProps<IconProps>;
    Vector39886990?: PrimitiveOverrideProps<IconProps>;
    Vector39886991?: PrimitiveOverrideProps<IconProps>;
    "robot-modern-flat-style-vector-removebg-preview 2"?: PrimitiveOverrideProps<ImageProps>;
    Vector39886993?: PrimitiveOverrideProps<IconProps>;
    "close_24dp_5F6368_FILL0_wght400_GRAD0_opsz24 2"?: PrimitiveOverrideProps<ViewProps>;
    Vector39886995?: PrimitiveOverrideProps<IconProps>;
    Vector39886996?: PrimitiveOverrideProps<IconProps>;
    Vector39886997?: PrimitiveOverrideProps<IconProps>;
    "AvatarPerfil 1"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 20"?: PrimitiveOverrideProps<ViewProps>;
    Button40901317?: PrimitiveOverrideProps<ButtonProps>;
    Button40901322?: PrimitiveOverrideProps<ButtonProps>;
    Button40901327?: PrimitiveOverrideProps<ButtonProps>;
} & EscapeHatchProps;
export declare type Home5Props = React.PropsWithChildren<Partial<ViewProps> & {
    bancoImagens?: BancoImagens;
} & {
    overrides?: Home5OverridesProps | undefined | null;
}>;
export default function Home5(props: Home5Props): React.ReactElement;
