/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { ButtonProps, IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type Home3OverridesProps = {
    Home3?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 26"?: PrimitiveOverrideProps<ViewProps>;
    "foto 1"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 20"?: PrimitiveOverrideProps<ViewProps>;
    Button40981936?: PrimitiveOverrideProps<ButtonProps>;
    Button40981937?: PrimitiveOverrideProps<ButtonProps>;
    Button40981938?: PrimitiveOverrideProps<ButtonProps>;
    "Group 68"?: PrimitiveOverrideProps<ViewProps>;
    "Group 381"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 140"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 19"?: PrimitiveOverrideProps<ViewProps>;
    "logo_branca_conecta 1"?: PrimitiveOverrideProps<ImageProps>;
    Vector41002407?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 139"?: PrimitiveOverrideProps<ViewProps>;
    Entrar?: PrimitiveOverrideProps<TextProps>;
    Ajuda?: PrimitiveOverrideProps<TextProps>;
    Vector40421048?: PrimitiveOverrideProps<IconProps>;
    Vector40421049?: PrimitiveOverrideProps<IconProps>;
    Alarm?: PrimitiveOverrideProps<ImageProps>;
    "Cadastrar-se"?: PrimitiveOverrideProps<TextProps>;
    "Conecte-se com oportunidades que valorizam suas habilidades"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 184"?: PrimitiveOverrideProps<ViewProps>;
    Button40421054?: PrimitiveOverrideProps<ButtonProps>;
    "Line 47"?: PrimitiveOverrideProps<IconProps>;
    "Line 48"?: PrimitiveOverrideProps<IconProps>;
    "SearchIcon 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector40421058?: PrimitiveOverrideProps<IconProps>;
    "Cargo | Habilidade"?: PrimitiveOverrideProps<TextProps>;
    "Cidade | Estado"?: PrimitiveOverrideProps<TextProps>;
    "Todas categorias"?: PrimitiveOverrideProps<TextProps>;
    Vector40421062?: PrimitiveOverrideProps<IconProps>;
    Vector40421063?: PrimitiveOverrideProps<IconProps>;
    "+40421064"?: PrimitiveOverrideProps<TextProps>;
    "+40421065"?: PrimitiveOverrideProps<TextProps>;
    "+40421066"?: PrimitiveOverrideProps<TextProps>;
    "+40421067"?: PrimitiveOverrideProps<TextProps>;
    "Group 400"?: PrimitiveOverrideProps<ViewProps>;
    "undraw_website_5bo8 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector40421070?: PrimitiveOverrideProps<IconProps>;
    Vector40421071?: PrimitiveOverrideProps<IconProps>;
    Vector40421072?: PrimitiveOverrideProps<IconProps>;
    Vector40421073?: PrimitiveOverrideProps<IconProps>;
    Vector40421074?: PrimitiveOverrideProps<IconProps>;
    Vector40421075?: PrimitiveOverrideProps<IconProps>;
    Vector40421076?: PrimitiveOverrideProps<IconProps>;
    Vector40421077?: PrimitiveOverrideProps<IconProps>;
    Vector40421078?: PrimitiveOverrideProps<IconProps>;
    Vector40421079?: PrimitiveOverrideProps<IconProps>;
    "logo_branca_conecta 4"?: PrimitiveOverrideProps<ImageProps>;
    Vector40421081?: PrimitiveOverrideProps<IconProps>;
    Vector40421082?: PrimitiveOverrideProps<IconProps>;
    Vector40421083?: PrimitiveOverrideProps<IconProps>;
    Vector40421084?: PrimitiveOverrideProps<IconProps>;
    Vector40421085?: PrimitiveOverrideProps<IconProps>;
    Vector40421086?: PrimitiveOverrideProps<IconProps>;
    Vector40421087?: PrimitiveOverrideProps<IconProps>;
    Vector40421088?: PrimitiveOverrideProps<IconProps>;
    Vector40421089?: PrimitiveOverrideProps<IconProps>;
    Vector40421090?: PrimitiveOverrideProps<IconProps>;
    Vector40421091?: PrimitiveOverrideProps<IconProps>;
    Vector40421092?: PrimitiveOverrideProps<IconProps>;
    "Sobre n\u00F3s"?: PrimitiveOverrideProps<TextProps>;
    "Sabemos que pessoas com TEA possuem certas limita\u00E7\u00F5es, como a necessidade de interfaces mais simples e menos sobrecarregadas de informa\u00E7\u00E3o. Assim, criamos a Conecta+, uma plataforma que conecta empregadores e candidatos com TEA, promovendo a inclus\u00E3o no mercado de trabalho."?: PrimitiveOverrideProps<TextProps>;
    "Categorias de vagas:"?: PrimitiveOverrideProps<TextProps>;
    "Group 428"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 9440421097"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 96"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 9440421099"?: PrimitiveOverrideProps<ViewProps>;
    image40421100?: PrimitiveOverrideProps<ViewProps>;
    image40421101?: PrimitiveOverrideProps<ViewProps>;
    "Sa\u00FAde"?: PrimitiveOverrideProps<TextProps>;
    Tecnologia?: PrimitiveOverrideProps<TextProps>;
    Design40421104?: PrimitiveOverrideProps<TextProps>;
    Vector40421105?: PrimitiveOverrideProps<IconProps>;
    Vector40421106?: PrimitiveOverrideProps<IconProps>;
    Vector40421107?: PrimitiveOverrideProps<IconProps>;
    Design40421108?: PrimitiveOverrideProps<TextProps>;
    "ArrowRightIcon 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector40421110?: PrimitiveOverrideProps<IconProps>;
    "ArrowRightIcon 2"?: PrimitiveOverrideProps<ViewProps>;
    Vector40421112?: PrimitiveOverrideProps<IconProps>;
    "Group 69"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 29"?: PrimitiveOverrideProps<ViewProps>;
    Temas?: PrimitiveOverrideProps<TextProps>;
    "Tamanho da fonte"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 30"?: PrimitiveOverrideProps<ViewProps>;
    Button40421118?: PrimitiveOverrideProps<ButtonProps>;
    Button40421119?: PrimitiveOverrideProps<ButtonProps>;
    "Seguir tema do sistema operacional"?: PrimitiveOverrideProps<TextProps>;
    "<"?: PrimitiveOverrideProps<TextProps>;
    "ThemeIcon 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector40421142?: PrimitiveOverrideProps<IconProps>;
    "chevron_right_24dp_E8EAED_FILL0_wght400_GRAD0_opsz24 2"?: PrimitiveOverrideProps<ViewProps>;
    Vector40421124?: PrimitiveOverrideProps<IconProps>;
    "\uD83D\uDD12Icon"?: PrimitiveOverrideProps<ViewProps>;
} & EscapeHatchProps;
export declare type Home3Props = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: Home3OverridesProps | undefined | null;
}>;
export default function Home3(props: Home3Props): React.ReactElement;
