/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { BancoImagens } from "../models";
import { ButtonProps, IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type Home4OverridesProps = {
    Home4?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 26"?: PrimitiveOverrideProps<ViewProps>;
    "foto 1"?: PrimitiveOverrideProps<ViewProps>;
    "Group 68"?: PrimitiveOverrideProps<ViewProps>;
    "Group 381"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 19"?: PrimitiveOverrideProps<ViewProps>;
    "logo_branca_conecta 1"?: PrimitiveOverrideProps<ImageProps>;
    Vector41002390?: PrimitiveOverrideProps<IconProps>;
    Vector39887014?: PrimitiveOverrideProps<IconProps>;
    Ajuda?: PrimitiveOverrideProps<TextProps>;
    "Conecte-se com oportunidades que valorizam suas habilidades"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 184"?: PrimitiveOverrideProps<ViewProps>;
    Button39887018?: PrimitiveOverrideProps<ButtonProps>;
    "Line 47"?: PrimitiveOverrideProps<IconProps>;
    "Line 48"?: PrimitiveOverrideProps<IconProps>;
    "Cargo | Habilidade"?: PrimitiveOverrideProps<TextProps>;
    "Cidade | Estado"?: PrimitiveOverrideProps<TextProps>;
    "Todas categorias"?: PrimitiveOverrideProps<TextProps>;
    "+39887024"?: PrimitiveOverrideProps<TextProps>;
    "+39887025"?: PrimitiveOverrideProps<TextProps>;
    "+39887026"?: PrimitiveOverrideProps<TextProps>;
    "+39887027"?: PrimitiveOverrideProps<TextProps>;
    "Group 400"?: PrimitiveOverrideProps<ViewProps>;
    "undraw_website_5bo8 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39887030?: PrimitiveOverrideProps<IconProps>;
    Vector39887031?: PrimitiveOverrideProps<IconProps>;
    Vector39887032?: PrimitiveOverrideProps<IconProps>;
    Vector39887033?: PrimitiveOverrideProps<IconProps>;
    Vector39887034?: PrimitiveOverrideProps<IconProps>;
    Vector39887035?: PrimitiveOverrideProps<IconProps>;
    Vector39887036?: PrimitiveOverrideProps<IconProps>;
    Vector39887037?: PrimitiveOverrideProps<IconProps>;
    Vector39887038?: PrimitiveOverrideProps<IconProps>;
    Vector39887039?: PrimitiveOverrideProps<IconProps>;
    "logo_branca_conecta 3"?: PrimitiveOverrideProps<ImageProps>;
    Vector39887041?: PrimitiveOverrideProps<IconProps>;
    Vector39887042?: PrimitiveOverrideProps<IconProps>;
    Vector39887043?: PrimitiveOverrideProps<IconProps>;
    Vector39887044?: PrimitiveOverrideProps<IconProps>;
    Vector39887045?: PrimitiveOverrideProps<IconProps>;
    Vector39887046?: PrimitiveOverrideProps<IconProps>;
    Vector39887047?: PrimitiveOverrideProps<IconProps>;
    Vector39887048?: PrimitiveOverrideProps<IconProps>;
    Vector39887049?: PrimitiveOverrideProps<IconProps>;
    Vector39887050?: PrimitiveOverrideProps<IconProps>;
    Vector39887051?: PrimitiveOverrideProps<IconProps>;
    Vector39887052?: PrimitiveOverrideProps<IconProps>;
    "Sobre n\u00F3s"?: PrimitiveOverrideProps<TextProps>;
    "Sabemos que pessoas com TEA possuem certas limita\u00E7\u00F5es, como a necessidade de interfaces mais simples e menos sobrecarregadas de informa\u00E7\u00E3o. Assim, criamos a Conecta+, uma plataforma que conecta empregadores e candidatos com TEA, promovendo a inclus\u00E3o no mercado de trabalho."?: PrimitiveOverrideProps<TextProps>;
    "Categorias de vagas:"?: PrimitiveOverrideProps<TextProps>;
    "Group 427"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 9439887057"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 96"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 9439887059"?: PrimitiveOverrideProps<ViewProps>;
    image39887060?: PrimitiveOverrideProps<ViewProps>;
    image39887061?: PrimitiveOverrideProps<ViewProps>;
    "Sa\u00FAde"?: PrimitiveOverrideProps<TextProps>;
    Tecnologia?: PrimitiveOverrideProps<TextProps>;
    Design?: PrimitiveOverrideProps<TextProps>;
    Vector39887065?: PrimitiveOverrideProps<IconProps>;
    Vector39887066?: PrimitiveOverrideProps<IconProps>;
    Vector39887067?: PrimitiveOverrideProps<IconProps>;
    Vector39887068?: PrimitiveOverrideProps<IconProps>;
    Vector39887069?: PrimitiveOverrideProps<IconProps>;
    "SearchIcon 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39887072?: PrimitiveOverrideProps<IconProps>;
    Vector39887073?: PrimitiveOverrideProps<IconProps>;
    Vector39887074?: PrimitiveOverrideProps<IconProps>;
    Vector39887075?: PrimitiveOverrideProps<IconProps>;
    "ArrowRightIcon 139887076"?: PrimitiveOverrideProps<ViewProps>;
    Vector39887077?: PrimitiveOverrideProps<IconProps>;
    "ArrowRightIcon 139887078"?: PrimitiveOverrideProps<ViewProps>;
    Vector39887079?: PrimitiveOverrideProps<IconProps>;
    "Group 429"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 188"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 189"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 190"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 191"?: PrimitiveOverrideProps<ViewProps>;
    Mensagem?: PrimitiveOverrideProps<TextProps>;
    "Oi, estou com dificuldades para carregar meu curr\u00EDculo na plataforma. Tentei o upload algumas vezes, mas n\u00E3o sei se o formato est\u00E1 correto ou se \u00E9 um problema t\u00E9cnico. Qual o formato e tamanho recomendados? H\u00E1 outra forma de adicionar o curr\u00EDculo? Agrade\u00E7o a ajuda!"?: PrimitiveOverrideProps<TextProps>;
    "Ol\u00E1! \uD83D\uDE0A Vamos ajudar com o upload do seu curr\u00EDculo! Para come\u00E7ar, acesse o seu perfil e clique em \u201CCarregar Curr\u00EDculo\u201D. Lembre-se de que ele deve estar em um dos formatos permitidos: PDF, DOC ou DOCX, com tamanho m\u00E1ximo de 5MB. Caso ainda encontre algum problema: Verifique a conex\u00E3o com a internet. Renomeie o arquivo para evitar caracteres especiais. Se o erro persistir, avise para que possamos ajudar voc\u00EA com alternativas! Boa sorte!"?: PrimitiveOverrideProps<TextProps>;
    "Line 54"?: PrimitiveOverrideProps<IconProps>;
    "undraw_chat_bot_re_e2gj 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39887090?: PrimitiveOverrideProps<IconProps>;
    Vector39887091?: PrimitiveOverrideProps<IconProps>;
    Vector39887092?: PrimitiveOverrideProps<IconProps>;
    Vector39887093?: PrimitiveOverrideProps<IconProps>;
    Vector39887094?: PrimitiveOverrideProps<IconProps>;
    Vector39887095?: PrimitiveOverrideProps<IconProps>;
    Vector39887096?: PrimitiveOverrideProps<IconProps>;
    Vector39887097?: PrimitiveOverrideProps<IconProps>;
    Vector39887098?: PrimitiveOverrideProps<IconProps>;
    Vector39887099?: PrimitiveOverrideProps<IconProps>;
    Vector39887100?: PrimitiveOverrideProps<IconProps>;
    Vector39887101?: PrimitiveOverrideProps<IconProps>;
    Vector39887102?: PrimitiveOverrideProps<IconProps>;
    Vector39887103?: PrimitiveOverrideProps<IconProps>;
    Vector39887104?: PrimitiveOverrideProps<IconProps>;
    Vector39887105?: PrimitiveOverrideProps<IconProps>;
    Vector39887106?: PrimitiveOverrideProps<IconProps>;
    Vector39887107?: PrimitiveOverrideProps<IconProps>;
    Vector39887108?: PrimitiveOverrideProps<IconProps>;
    Vector39887109?: PrimitiveOverrideProps<IconProps>;
    Vector39887110?: PrimitiveOverrideProps<IconProps>;
    Vector39887111?: PrimitiveOverrideProps<IconProps>;
    Vector39887112?: PrimitiveOverrideProps<IconProps>;
    Vector39887113?: PrimitiveOverrideProps<IconProps>;
    Vector39887114?: PrimitiveOverrideProps<IconProps>;
    Vector39887115?: PrimitiveOverrideProps<IconProps>;
    Vector39887116?: PrimitiveOverrideProps<IconProps>;
    Vector39887117?: PrimitiveOverrideProps<IconProps>;
    Vector39887118?: PrimitiveOverrideProps<IconProps>;
    Vector39887119?: PrimitiveOverrideProps<IconProps>;
    Vector39887120?: PrimitiveOverrideProps<IconProps>;
    Vector39887121?: PrimitiveOverrideProps<IconProps>;
    Vector39887122?: PrimitiveOverrideProps<IconProps>;
    Vector39887123?: PrimitiveOverrideProps<IconProps>;
    Vector39887124?: PrimitiveOverrideProps<IconProps>;
    "robot-modern-flat-style-vector-removebg-preview 2"?: PrimitiveOverrideProps<ImageProps>;
    "robot-modern-flat-style-vector-removebg-preview 33995651"?: PrimitiveOverrideProps<ImageProps>;
    "close_24dp_5F6368_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39887128?: PrimitiveOverrideProps<IconProps>;
    Vector39887129?: PrimitiveOverrideProps<IconProps>;
    "robot-modern-flat-style-vector-removebg-preview 339887130"?: PrimitiveOverrideProps<ImageProps>;
    "Jo\u00E3o Pedro Borges"?: PrimitiveOverrideProps<TextProps>;
    "AvatarPerfil 1"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 20"?: PrimitiveOverrideProps<ViewProps>;
    Button40932107?: PrimitiveOverrideProps<ButtonProps>;
    Button40932108?: PrimitiveOverrideProps<ButtonProps>;
    Button40932109?: PrimitiveOverrideProps<ButtonProps>;
} & EscapeHatchProps;
export declare type Home4Props = React.PropsWithChildren<Partial<ViewProps> & {
    bancoImagens?: BancoImagens;
} & {
    overrides?: Home4OverridesProps | undefined | null;
}>;
export default function Home4(props: Home4Props): React.ReactElement;
