/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { ButtonProps, FlexProps, IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type Home1OverridesProps = {
    Home1?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 26"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 19"?: PrimitiveOverrideProps<ViewProps>;
    "logo_branca_conecta 2"?: PrimitiveOverrideProps<ImageProps>;
    Button39883872?: PrimitiveOverrideProps<ButtonProps>;
    Button39883876?: PrimitiveOverrideProps<ButtonProps>;
    "Conecte-se com oportunidades que valorizam suas habilidades"?: PrimitiveOverrideProps<TextProps>;
    "+"?: PrimitiveOverrideProps<TextProps>;
    "Frame 434"?: PrimitiveOverrideProps<ViewProps>;
    "foto 1"?: PrimitiveOverrideProps<ViewProps>;
    "undraw_website_5bo8 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39883895?: PrimitiveOverrideProps<IconProps>;
    Vector39883896?: PrimitiveOverrideProps<IconProps>;
    Vector39883897?: PrimitiveOverrideProps<IconProps>;
    Vector39883898?: PrimitiveOverrideProps<IconProps>;
    Vector39883899?: PrimitiveOverrideProps<IconProps>;
    Vector39883900?: PrimitiveOverrideProps<IconProps>;
    Vector39883901?: PrimitiveOverrideProps<IconProps>;
    Vector39883902?: PrimitiveOverrideProps<IconProps>;
    Vector39883903?: PrimitiveOverrideProps<IconProps>;
    Vector39883904?: PrimitiveOverrideProps<IconProps>;
    "logo_branca_conecta 3"?: PrimitiveOverrideProps<ImageProps>;
    Vector39883906?: PrimitiveOverrideProps<IconProps>;
    Vector39883907?: PrimitiveOverrideProps<IconProps>;
    Vector39883908?: PrimitiveOverrideProps<IconProps>;
    Vector39883909?: PrimitiveOverrideProps<IconProps>;
    Vector39883910?: PrimitiveOverrideProps<IconProps>;
    Vector39883911?: PrimitiveOverrideProps<IconProps>;
    Vector39883912?: PrimitiveOverrideProps<IconProps>;
    Vector39883913?: PrimitiveOverrideProps<IconProps>;
    Vector39883914?: PrimitiveOverrideProps<IconProps>;
    Vector39883915?: PrimitiveOverrideProps<IconProps>;
    Vector39883916?: PrimitiveOverrideProps<IconProps>;
    Vector39883917?: PrimitiveOverrideProps<IconProps>;
    "Sobre n\u00F3s"?: PrimitiveOverrideProps<TextProps>;
    "Sabemos que pessoas com TEA possuem certas limita\u00E7\u00F5es, como a necessidade de interfaces mais simples e menos sobrecarregadas de informa\u00E7\u00E3o. Assim, criamos a Conecta+, uma plataforma que conecta empregadores e candidatos com TEA, promovendo a inclus\u00E3o no mercado de trabalho."?: PrimitiveOverrideProps<TextProps>;
    "Categorias de vagas:"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 184"?: PrimitiveOverrideProps<ViewProps>;
    Input?: PrimitiveOverrideProps<FlexProps>;
    placeholder?: PrimitiveOverrideProps<TextProps>;
    "\uD83D\uDD12Icon"?: PrimitiveOverrideProps<ViewProps>;
    Button39883884?: PrimitiveOverrideProps<ButtonProps>;
    "Line 47"?: PrimitiveOverrideProps<IconProps>;
    "Line 48"?: PrimitiveOverrideProps<IconProps>;
    "Cargo | Habilidade"?: PrimitiveOverrideProps<TextProps>;
    "Cidade | Estado"?: PrimitiveOverrideProps<TextProps>;
    "SearchIcon 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39883937?: PrimitiveOverrideProps<IconProps>;
    "ArrowRightIcon 139883940"?: PrimitiveOverrideProps<ViewProps>;
    Vector39883941?: PrimitiveOverrideProps<IconProps>;
    "ArrowRightIcon 139883942"?: PrimitiveOverrideProps<ViewProps>;
    Vector39883943?: PrimitiveOverrideProps<IconProps>;
    MenuGroup?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 20"?: PrimitiveOverrideProps<ViewProps>;
    Button40932135?: PrimitiveOverrideProps<ButtonProps>;
    Button40932136?: PrimitiveOverrideProps<ButtonProps>;
    Button40932137?: PrimitiveOverrideProps<ButtonProps>;
    "ArrowRightIcon 3"?: PrimitiveOverrideProps<ViewProps>;
    Vector42151351?: PrimitiveOverrideProps<IconProps>;
    "Suas ultimas vagas"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 152"?: PrimitiveOverrideProps<IconProps>;
    "1.783 avalia\u00E7\u00F5es"?: PrimitiveOverrideProps<TextProps>;
    "S\u00E3o Paulo - SP"?: PrimitiveOverrideProps<TextProps>;
    "R$ 5.200,00"?: PrimitiveOverrideProps<TextProps>;
    "H\u00EDbrido"?: PrimitiveOverrideProps<TextProps>;
    "ANALISTA DE DADOS"?: PrimitiveOverrideProps<TextProps>;
    "image 7"?: PrimitiveOverrideProps<ImageProps>;
    "4,5"?: PrimitiveOverrideProps<TextProps>;
    "star_24dp_000000_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector42091947?: PrimitiveOverrideProps<IconProps>;
    "REKTR TEC"?: PrimitiveOverrideProps<TextProps>;
    "new_releases_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector42091950?: PrimitiveOverrideProps<IconProps>;
    Vector42091951?: PrimitiveOverrideProps<IconProps>;
    "undraw_undraw_undraw_undraw_undraw_undraw_undraw_undraw_users_per_minute_1e4q_t22j_-1-_0ngf_-1-_27dv_30ul_legv_-1-_il1l_-2-_0jip 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector42091953?: PrimitiveOverrideProps<IconProps>;
    Vector42091954?: PrimitiveOverrideProps<IconProps>;
    Vector42091955?: PrimitiveOverrideProps<IconProps>;
    Vector42091956?: PrimitiveOverrideProps<IconProps>;
    Vector42091957?: PrimitiveOverrideProps<IconProps>;
    Vector42091958?: PrimitiveOverrideProps<IconProps>;
    Vector42091959?: PrimitiveOverrideProps<IconProps>;
    Vector42091960?: PrimitiveOverrideProps<IconProps>;
    Vector42091961?: PrimitiveOverrideProps<IconProps>;
    Vector42091962?: PrimitiveOverrideProps<IconProps>;
    Vector42091963?: PrimitiveOverrideProps<IconProps>;
    Vector42091964?: PrimitiveOverrideProps<IconProps>;
    Vector42091965?: PrimitiveOverrideProps<IconProps>;
    Vector42091966?: PrimitiveOverrideProps<IconProps>;
    Vector42091967?: PrimitiveOverrideProps<IconProps>;
    Vector42091968?: PrimitiveOverrideProps<IconProps>;
    Vector42091969?: PrimitiveOverrideProps<IconProps>;
    Vector42091970?: PrimitiveOverrideProps<IconProps>;
    Vector42091971?: PrimitiveOverrideProps<IconProps>;
    Vector42091972?: PrimitiveOverrideProps<IconProps>;
    Vector42091973?: PrimitiveOverrideProps<IconProps>;
    "uuid-b665f492-9b4b-4e5e-8d83-e9db200bf715-44-44-44-72-164-43-39-119"?: PrimitiveOverrideProps<IconProps>;
    Vector42091975?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 9439883922"?: PrimitiveOverrideProps<ViewProps>;
    image?: PrimitiveOverrideProps<IconProps>;
    "Sa\u00FAde"?: PrimitiveOverrideProps<TextProps>;
    Tecnologia?: PrimitiveOverrideProps<TextProps>;
    Vector39883930?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 9439883924"?: PrimitiveOverrideProps<ViewProps>;
    Design?: PrimitiveOverrideProps<TextProps>;
    Vector39883932?: PrimitiveOverrideProps<IconProps>;
    Vector39883931?: PrimitiveOverrideProps<IconProps>;
    Vector39883877?: PrimitiveOverrideProps<IconProps>;
    Ajuda?: PrimitiveOverrideProps<TextProps>;
    Vector39883933?: PrimitiveOverrideProps<IconProps>;
    Vector39883934?: PrimitiveOverrideProps<IconProps>;
    Vector40892265?: PrimitiveOverrideProps<IconProps>;
    Vector39883939?: PrimitiveOverrideProps<IconProps>;
    Vector39883938?: PrimitiveOverrideProps<IconProps>;
} & EscapeHatchProps;
export declare type Home1Props = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: Home1OverridesProps | undefined | null;
}>;
export default function Home1(props: Home1Props): React.ReactElement;
