/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { ButtonProps, IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type Home6OverridesProps = {
    Home6?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 26"?: PrimitiveOverrideProps<ViewProps>;
    "foto 1"?: PrimitiveOverrideProps<ViewProps>;
    "Conecte-se com oportunidades que valorizam suas habilidades"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 184"?: PrimitiveOverrideProps<ViewProps>;
    Button40661234?: PrimitiveOverrideProps<ButtonProps>;
    "Line 47"?: PrimitiveOverrideProps<IconProps>;
    "Line 48"?: PrimitiveOverrideProps<IconProps>;
    "Cargo | Habilidade"?: PrimitiveOverrideProps<TextProps>;
    "Cidade | Estado"?: PrimitiveOverrideProps<TextProps>;
    "Todas categorias"?: PrimitiveOverrideProps<TextProps>;
    "chevron_backward_24dp_5F6368_FILL0_wght400_GRAD0_opsz24 2"?: PrimitiveOverrideProps<ViewProps>;
    Vector40661241?: PrimitiveOverrideProps<IconProps>;
    "+40661242"?: PrimitiveOverrideProps<TextProps>;
    "+40661243"?: PrimitiveOverrideProps<TextProps>;
    "+40661244"?: PrimitiveOverrideProps<TextProps>;
    "+40661245"?: PrimitiveOverrideProps<TextProps>;
    "Categorias de vagas:"?: PrimitiveOverrideProps<TextProps>;
    "Suas ultimas vagas"?: PrimitiveOverrideProps<TextProps>;
    "Group 87"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 9440661249"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 96"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 9440661251"?: PrimitiveOverrideProps<ViewProps>;
    image40661252?: PrimitiveOverrideProps<ViewProps>;
    image40661253?: PrimitiveOverrideProps<ViewProps>;
    "Sa\u00FAde"?: PrimitiveOverrideProps<TextProps>;
    Tecnologia?: PrimitiveOverrideProps<TextProps>;
    Vector40661256?: PrimitiveOverrideProps<IconProps>;
    Vector40661257?: PrimitiveOverrideProps<IconProps>;
    Vector40661258?: PrimitiveOverrideProps<IconProps>;
    Design?: PrimitiveOverrideProps<TextProps>;
    "chevron_backward_24dp_5F6368_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector40661261?: PrimitiveOverrideProps<IconProps>;
    "Group 423"?: PrimitiveOverrideProps<ViewProps>;
    "Group 68"?: PrimitiveOverrideProps<ViewProps>;
    "Group 381"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 19"?: PrimitiveOverrideProps<ViewProps>;
    "logo_branca_conecta 1"?: PrimitiveOverrideProps<ImageProps>;
    Vector40901313?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 139"?: PrimitiveOverrideProps<IconProps>;
    Ajuda?: PrimitiveOverrideProps<TextProps>;
    "Jo\u00E3o Pedro Borges"?: PrimitiveOverrideProps<TextProps>;
    Vector40661271?: PrimitiveOverrideProps<IconProps>;
    Vector40661272?: PrimitiveOverrideProps<IconProps>;
    Vector40661273?: PrimitiveOverrideProps<IconProps>;
    "Line 49"?: PrimitiveOverrideProps<IconProps>;
    "Group 401"?: PrimitiveOverrideProps<ViewProps>;
    "Group 399"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 152"?: PrimitiveOverrideProps<IconProps>;
    "1.783 avalia\u00E7\u00F5es"?: PrimitiveOverrideProps<TextProps>;
    "S\u00E3o Paulo - SP"?: PrimitiveOverrideProps<TextProps>;
    "R$ 5.200,00"?: PrimitiveOverrideProps<TextProps>;
    "H\u00EDbrido"?: PrimitiveOverrideProps<TextProps>;
    "ANALISTA DE DADOS"?: PrimitiveOverrideProps<TextProps>;
    "image 7"?: PrimitiveOverrideProps<ImageProps>;
    "4,5"?: PrimitiveOverrideProps<TextProps>;
    "star_24dp_000000_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector40661286?: PrimitiveOverrideProps<IconProps>;
    "REKTR TEC"?: PrimitiveOverrideProps<TextProps>;
    "new_releases_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector40661289?: PrimitiveOverrideProps<IconProps>;
    Vector40701076?: PrimitiveOverrideProps<IconProps>;
    "robot-modern-flat-style-vector-removebg-preview 1"?: PrimitiveOverrideProps<ImageProps>;
    "location_on_24dp_5F6368_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector40661293?: PrimitiveOverrideProps<IconProps>;
    Vector40661294?: PrimitiveOverrideProps<IconProps>;
    Vector40661295?: PrimitiveOverrideProps<IconProps>;
    "AvatarPerfil 1"?: PrimitiveOverrideProps<ImageProps>;
    Button40661297?: PrimitiveOverrideProps<ButtonProps>;
    "undraw_undraw_undraw_undraw_undraw_undraw_undraw_undraw_users_per_minute_1e4q_t22j_-1-_0ngf_-1-_27dv_30ul_legv_-1-_il1l_-2-_0jip 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector40661299?: PrimitiveOverrideProps<IconProps>;
    Vector40661300?: PrimitiveOverrideProps<IconProps>;
    Vector40661301?: PrimitiveOverrideProps<IconProps>;
    Vector40661302?: PrimitiveOverrideProps<IconProps>;
    Vector40661303?: PrimitiveOverrideProps<IconProps>;
    Vector40661304?: PrimitiveOverrideProps<IconProps>;
    Vector40661305?: PrimitiveOverrideProps<IconProps>;
    Vector40661306?: PrimitiveOverrideProps<IconProps>;
    Vector40661307?: PrimitiveOverrideProps<IconProps>;
    Vector40661308?: PrimitiveOverrideProps<IconProps>;
    Vector40661309?: PrimitiveOverrideProps<IconProps>;
    Vector40661310?: PrimitiveOverrideProps<IconProps>;
    Vector40661311?: PrimitiveOverrideProps<IconProps>;
    Vector40661312?: PrimitiveOverrideProps<IconProps>;
    Vector40661313?: PrimitiveOverrideProps<IconProps>;
    Vector40661314?: PrimitiveOverrideProps<IconProps>;
    Vector40661315?: PrimitiveOverrideProps<IconProps>;
    Vector40661316?: PrimitiveOverrideProps<IconProps>;
    Vector40661317?: PrimitiveOverrideProps<IconProps>;
    Vector40661318?: PrimitiveOverrideProps<IconProps>;
    Vector40661319?: PrimitiveOverrideProps<IconProps>;
    "uuid-b665f492-9b4b-4e5e-8d83-e9db200bf715-44-44-44-72-164-43-39-119"?: PrimitiveOverrideProps<IconProps>;
    Vector40661321?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 185"?: PrimitiveOverrideProps<ViewProps>;
    Button40932121?: PrimitiveOverrideProps<ButtonProps>;
    Button40932122?: PrimitiveOverrideProps<ButtonProps>;
    Button40932123?: PrimitiveOverrideProps<ButtonProps>;
} & EscapeHatchProps;
export declare type Home6Props = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: Home6OverridesProps | undefined | null;
}>;
export default function Home6(props: Home6Props): React.ReactElement;
