/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { BancoImagens } from "../models";
import { ButtonProps, IconProps, ImageProps, SelectFieldProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type MeuPerfil4OverridesProps = {
    MeuPerfil4?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 27"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 26"?: PrimitiveOverrideProps<ViewProps>;
    "Noise & Texture"?: PrimitiveOverrideProps<ImageProps>;
    "Group 408"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 122"?: PrimitiveOverrideProps<ViewProps>;
    "AvatarPerfil 141002066"?: PrimitiveOverrideProps<ImageProps>;
    "Ellipse 105"?: PrimitiveOverrideProps<IconProps>;
    "edit_24dp_5F6368_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39883046?: PrimitiveOverrideProps<IconProps>;
    "Jo\u00E3o Pedro Borges39883047"?: PrimitiveOverrideProps<TextProps>;
    "Group 404"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 12339883049"?: PrimitiveOverrideProps<ViewProps>;
    Status?: PrimitiveOverrideProps<TextProps>;
    SelectField?: PrimitiveOverrideProps<SelectFieldProps>;
    "Group 407"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 125"?: PrimitiveOverrideProps<ViewProps>;
    "Acompanhe o preenchimento de seu curr\u00EDculo aqui!"?: PrimitiveOverrideProps<TextProps>;
    Button39883057?: PrimitiveOverrideProps<ButtonProps>;
    Button41201345?: PrimitiveOverrideProps<ButtonProps>;
    "Curr\u00EDculo"?: PrimitiveOverrideProps<TextProps>;
    "Voc\u00EA est\u00E1 quase l\u00E1, falta pouco para o seu curr\u00EDculo ficar pronto!"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 127"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 142"?: PrimitiveOverrideProps<ViewProps>;
    "60%"?: PrimitiveOverrideProps<TextProps>;
    "Group 406"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 126"?: PrimitiveOverrideProps<ViewProps>;
    "Escolaridade / Forma\u00E7\u00E3o"?: PrimitiveOverrideProps<TextProps>;
    "Curso:"?: PrimitiveOverrideProps<TextProps>;
    "Per\u00EDodo do Curso:"?: PrimitiveOverrideProps<TextProps>;
    "Ano / Semestre:"?: PrimitiveOverrideProps<TextProps>;
    "Fatec Ferraz de Vasconcelos"?: PrimitiveOverrideProps<TextProps>;
    "ADS - An\u00E1lise e Desenvolvimento de Sistemas"?: PrimitiveOverrideProps<TextProps>;
    Vespertino?: PrimitiveOverrideProps<TextProps>;
    "2\u00B0 Semestre"?: PrimitiveOverrideProps<TextProps>;
    Vector41211328?: PrimitiveOverrideProps<IconProps>;
    "Institui\u00E7\u00E3o de Ensino:"?: PrimitiveOverrideProps<TextProps>;
    "Group 405"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 12339883080"?: PrimitiveOverrideProps<ViewProps>;
    "Telefone: (11) 91234-6789"?: PrimitiveOverrideProps<TextProps>;
    "E-mail: joaoborges.2010@gmail.com"?: PrimitiveOverrideProps<TextProps>;
    "N\u00EDvel da Condi\u00E7\u00E3o: N\u00EDvel 2"?: PrimitiveOverrideProps<TextProps>;
    "Informa\u00E7\u00F5es do Usu\u00E1rio"?: PrimitiveOverrideProps<TextProps>;
    "Sobre Mim:"?: PrimitiveOverrideProps<TextProps>;
    "PuzzleBlackIcon 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector41122118?: PrimitiveOverrideProps<IconProps>;
    "Line 52"?: PrimitiveOverrideProps<IconProps>;
    "PhoneBlackIcon 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector41122113?: PrimitiveOverrideProps<IconProps>;
    Vector41122115?: PrimitiveOverrideProps<IconProps>;
    Vector41122107?: PrimitiveOverrideProps<IconProps>;
    Vector41122120?: PrimitiveOverrideProps<IconProps>;
    "Sou Jo\u00E3o, desenvolvedor front-end apaixonado por tecnologia e sempre em busca de aprender. Gosto de resolver problemas e criar interfaces funcionais e bonitas. Busco oportunidades em empresas inclusivas onde eu possa crescer e fazer a diferen\u00E7a com meu trabalho."?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 19"?: PrimitiveOverrideProps<ViewProps>;
    "Group 431"?: PrimitiveOverrideProps<ViewProps>;
    Vector41051374?: PrimitiveOverrideProps<IconProps>;
    Vector41051375?: PrimitiveOverrideProps<IconProps>;
    Vector41051376?: PrimitiveOverrideProps<IconProps>;
    Ajuda?: PrimitiveOverrideProps<TextProps>;
    Vector41051378?: PrimitiveOverrideProps<IconProps>;
    "logo_branca_conecta 1"?: PrimitiveOverrideProps<ImageProps>;
    "+ 439883099"?: PrimitiveOverrideProps<TextProps>;
    "Line 28"?: PrimitiveOverrideProps<IconProps>;
    "Group 95"?: PrimitiveOverrideProps<ViewProps>;
    "Group 94"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 130"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131"?: PrimitiveOverrideProps<ViewProps>;
    Button39883105?: PrimitiveOverrideProps<ButtonProps>;
    Button39883106?: PrimitiveOverrideProps<ButtonProps>;
    "Suas Publica\u00E7\u00F5es"?: PrimitiveOverrideProps<TextProps>;
    "Poxaaa, que pena :( No momento voc\u00EA n\u00E3o est\u00E1 participando de nenhuma vaga, busque vagas na aba \u201CVagas de emprego\u201D"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 134"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 138"?: PrimitiveOverrideProps<ViewProps>;
    ".39883111"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 135"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 141"?: PrimitiveOverrideProps<ViewProps>;
    "Publica\u00E7\u00F5es"?: PrimitiveOverrideProps<TextProps>;
    Destaques?: PrimitiveOverrideProps<TextProps>;
    "Jo\u00E3o Pedro Borges39883116"?: PrimitiveOverrideProps<TextProps>;
    "Jo\u00E3o Pedro Borges39883117"?: PrimitiveOverrideProps<TextProps>;
    "...39883118"?: PrimitiveOverrideProps<TextProps>;
    "...39883119"?: PrimitiveOverrideProps<TextProps>;
    "Voc\u00EA39883120"?: PrimitiveOverrideProps<TextProps>;
    "Voc\u00EA39883121"?: PrimitiveOverrideProps<TextProps>;
    ".39883122"?: PrimitiveOverrideProps<TextProps>;
    image39883123?: PrimitiveOverrideProps<IconProps>;
    "AvatarPerfil 141042432"?: PrimitiveOverrideProps<ImageProps>;
    "Boa tarde amigos! Hoje tive a incr\u00EDvel oportunidade de visitar a sede da CityCorp, e posso dizer que essa experi\u00EAncia foi ...mais"?: PrimitiveOverrideProps<TextProps>;
    image39883128?: PrimitiveOverrideProps<ImageProps>;
    image39883129?: PrimitiveOverrideProps<ImageProps>;
    image39883130?: PrimitiveOverrideProps<ImageProps>;
    image39883131?: PrimitiveOverrideProps<ImageProps>;
    image39883132?: PrimitiveOverrideProps<ImageProps>;
    "+ 439883133"?: PrimitiveOverrideProps<TextProps>;
    "4 min"?: PrimitiveOverrideProps<TextProps>;
    "5 d"?: PrimitiveOverrideProps<TextProps>;
    "Jo\u00E3o Pedro Borges39883148"?: PrimitiveOverrideProps<TextProps>;
    "Group 420"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 160"?: PrimitiveOverrideProps<ViewProps>;
    "Upload de curr\u00EDculos"?: PrimitiveOverrideProps<TextProps>;
    Upload?: PrimitiveOverrideProps<TextProps>;
    x39883153?: PrimitiveOverrideProps<TextProps>;
    "Line 38"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 161"?: PrimitiveOverrideProps<ViewProps>;
    "JoaoBorguesCurriculo.pdf"?: PrimitiveOverrideProps<TextProps>;
    "Formatos permitidos: PDF, Doc, Docx | Tamanho M\u00E1ximo 5.0MB"?: PrimitiveOverrideProps<TextProps>;
    x39883158?: PrimitiveOverrideProps<TextProps>;
    Button39883159?: PrimitiveOverrideProps<ButtonProps>;
    Button39883160?: PrimitiveOverrideProps<ButtonProps>;
    "AvatarPerfil 14041865"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 21"?: PrimitiveOverrideProps<ViewProps>;
    Button41001989?: PrimitiveOverrideProps<ButtonProps>;
    Button41001990?: PrimitiveOverrideProps<ButtonProps>;
    Button41001991?: PrimitiveOverrideProps<ButtonProps>;
    Vector41201341?: PrimitiveOverrideProps<IconProps>;
    Vector41201342?: PrimitiveOverrideProps<IconProps>;
    Vector41201363?: PrimitiveOverrideProps<IconProps>;
    "ChatIconBlack 3"?: PrimitiveOverrideProps<ViewProps>;
    Vector41201365?: PrimitiveOverrideProps<IconProps>;
    "SendIconBlack 2"?: PrimitiveOverrideProps<ViewProps>;
    Vector41201367?: PrimitiveOverrideProps<IconProps>;
    Compartilhar?: PrimitiveOverrideProps<TextProps>;
    Gostei?: PrimitiveOverrideProps<TextProps>;
    Comentar?: PrimitiveOverrideProps<TextProps>;
} & EscapeHatchProps;
export declare type MeuPerfil4Props = React.PropsWithChildren<Partial<ViewProps> & {
    bancoImagens?: BancoImagens;
} & {
    overrides?: MeuPerfil4OverridesProps | undefined | null;
}>;
export default function MeuPerfil4(props: MeuPerfil4Props): React.ReactElement;
