/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { ButtonProps, IconProps, ImageProps, SelectFieldProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type MeuPerfil2OverridesProps = {
    MeuPerfil2?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 27"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 26"?: PrimitiveOverrideProps<ViewProps>;
    "Noise & Texture"?: PrimitiveOverrideProps<ImageProps>;
    "Group 408"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 122"?: PrimitiveOverrideProps<ViewProps>;
    "AvatarPerfil 141002064"?: PrimitiveOverrideProps<ImageProps>;
    "Ellipse 105"?: PrimitiveOverrideProps<IconProps>;
    "edit_24dp_5F6368_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39883410?: PrimitiveOverrideProps<IconProps>;
    "Jo\u00E3o Pedro Borges39883411"?: PrimitiveOverrideProps<TextProps>;
    "Group 404"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 12339883413"?: PrimitiveOverrideProps<ViewProps>;
    Status?: PrimitiveOverrideProps<TextProps>;
    SelectField?: PrimitiveOverrideProps<SelectFieldProps>;
    "Group 407"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 125"?: PrimitiveOverrideProps<ViewProps>;
    "Acompanhe o preenchimento de seu curr\u00EDculo aqui!"?: PrimitiveOverrideProps<TextProps>;
    Button39883420?: PrimitiveOverrideProps<ButtonProps>;
    "Rectangle 129"?: PrimitiveOverrideProps<ViewProps>;
    "Modelos de Curr\u00EDculos39883422"?: PrimitiveOverrideProps<TextProps>;
    "Curr\u00EDculo"?: PrimitiveOverrideProps<TextProps>;
    "Like Message"?: PrimitiveOverrideProps<ImageProps>;
    "Voc\u00EA est\u00E1 quase l\u00E1, falta pouco para o seu curr\u00EDculo ficar pronto!"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 127"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 142"?: PrimitiveOverrideProps<ViewProps>;
    "60%"?: PrimitiveOverrideProps<TextProps>;
    "Group 406"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 126"?: PrimitiveOverrideProps<ViewProps>;
    "Escolaridade / Forma\u00E7\u00E3o"?: PrimitiveOverrideProps<TextProps>;
    "Curso:"?: PrimitiveOverrideProps<TextProps>;
    "Per\u00EDodo do Curso:"?: PrimitiveOverrideProps<TextProps>;
    "Ano / Semestre:"?: PrimitiveOverrideProps<TextProps>;
    "Fatec Ferraz de Vasconcelos"?: PrimitiveOverrideProps<TextProps>;
    "ADS - An\u00E1lise e Desenvolvimento de Sistemas"?: PrimitiveOverrideProps<TextProps>;
    Vespertino?: PrimitiveOverrideProps<TextProps>;
    "2\u00B0 Semestre"?: PrimitiveOverrideProps<TextProps>;
    "Institui\u00E7\u00E3o de Ensino:"?: PrimitiveOverrideProps<TextProps>;
    "Group 405"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 12339883444"?: PrimitiveOverrideProps<ViewProps>;
    "Telefone: (11) 91234-6789"?: PrimitiveOverrideProps<TextProps>;
    "E-mail: joaoborges.2010@gmail.com"?: PrimitiveOverrideProps<TextProps>;
    "N\u00EDvel da Condi\u00E7\u00E3o: N\u00EDvel 2"?: PrimitiveOverrideProps<TextProps>;
    "Informa\u00E7\u00F5es do Usu\u00E1rio"?: PrimitiveOverrideProps<TextProps>;
    "Sobre Mim:"?: PrimitiveOverrideProps<TextProps>;
    "Line 52"?: PrimitiveOverrideProps<IconProps>;
    "Sou Jo\u00E3o, desenvolvedor front-end apaixonado por tecnologia e sempre em busca de aprender. Gosto de resolver problemas e criar interfaces funcionais e bonitas. Busco oportunidades em empresas inclusivas onde eu possa crescer e fazer a diferen\u00E7a com meu trabalho."?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 19"?: PrimitiveOverrideProps<ViewProps>;
    "Group 431"?: PrimitiveOverrideProps<ViewProps>;
    Vector41051367?: PrimitiveOverrideProps<IconProps>;
    Vector41051368?: PrimitiveOverrideProps<IconProps>;
    Vector41051369?: PrimitiveOverrideProps<IconProps>;
    Ajuda?: PrimitiveOverrideProps<TextProps>;
    Vector41051371?: PrimitiveOverrideProps<IconProps>;
    "logo_branca_conecta 1"?: PrimitiveOverrideProps<ImageProps>;
    "+ 439883462"?: PrimitiveOverrideProps<TextProps>;
    "Line 28"?: PrimitiveOverrideProps<IconProps>;
    "Group 95"?: PrimitiveOverrideProps<ViewProps>;
    "Group 9439883465"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13039883466"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13139883467"?: PrimitiveOverrideProps<ViewProps>;
    Button39883468?: PrimitiveOverrideProps<ButtonProps>;
    Button39883469?: PrimitiveOverrideProps<ButtonProps>;
    "Suas Publica\u00E7\u00F5es39883470"?: PrimitiveOverrideProps<TextProps>;
    "Poxaaa, que pena :( No momento voc\u00EA n\u00E3o est\u00E1 participando de nenhuma vaga, busque vagas na aba \u201CVagas de emprego\u201D39883471"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 13439883472"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13839883473"?: PrimitiveOverrideProps<ViewProps>;
    ".39883474"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 13539883475"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 14139883476"?: PrimitiveOverrideProps<ViewProps>;
    "Publica\u00E7\u00F5es39883477"?: PrimitiveOverrideProps<TextProps>;
    Destaques39883478?: PrimitiveOverrideProps<TextProps>;
    "Jo\u00E3o Pedro Borges39883479"?: PrimitiveOverrideProps<TextProps>;
    "Jo\u00E3o Pedro Borges39883480"?: PrimitiveOverrideProps<TextProps>;
    "...39883481"?: PrimitiveOverrideProps<TextProps>;
    "...39883482"?: PrimitiveOverrideProps<TextProps>;
    "Voc\u00EA39883483"?: PrimitiveOverrideProps<TextProps>;
    "Voc\u00EA39883484"?: PrimitiveOverrideProps<TextProps>;
    ".39883485"?: PrimitiveOverrideProps<TextProps>;
    "AvatarPerfil 241042426"?: PrimitiveOverrideProps<ImageProps>;
    "AvatarPerfil 141042424"?: PrimitiveOverrideProps<ImageProps>;
    "Boa tarde amigos! Hoje tive a incr\u00EDvel oportunidade de visitar a sede da CityCorp, e posso dizer que essa experi\u00EAncia foi ...mais39883488"?: PrimitiveOverrideProps<TextProps>;
    image39883491?: PrimitiveOverrideProps<ImageProps>;
    image39883492?: PrimitiveOverrideProps<ImageProps>;
    image39883493?: PrimitiveOverrideProps<ImageProps>;
    image39883494?: PrimitiveOverrideProps<ImageProps>;
    image39883495?: PrimitiveOverrideProps<ImageProps>;
    "+ 439883496"?: PrimitiveOverrideProps<TextProps>;
    "4 min39883506"?: PrimitiveOverrideProps<TextProps>;
    "5 d39883507"?: PrimitiveOverrideProps<TextProps>;
    "Jo\u00E3o Pedro Borges39883511"?: PrimitiveOverrideProps<TextProps>;
    "Group 420"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 160"?: PrimitiveOverrideProps<ViewProps>;
    "Modelos de Curr\u00EDculos39883514"?: PrimitiveOverrideProps<TextProps>;
    "Fa\u00E7a download dos modelos."?: PrimitiveOverrideProps<TextProps>;
    x?: PrimitiveOverrideProps<TextProps>;
    "Line 38"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 161"?: PrimitiveOverrideProps<ViewProps>;
    "Modelo de Curr\u00EDculo Simples - Aprendiz Modelo de Curr\u00EDculo Simples - Est\u00E1gio Modelo de Curr\u00EDculo com Foto"?: PrimitiveOverrideProps<TextProps>;
    Button39883520?: PrimitiveOverrideProps<ButtonProps>;
    "AvatarPerfil 14043873"?: PrimitiveOverrideProps<ImageProps>;
    "PuzzleBlackIcon 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector41201326?: PrimitiveOverrideProps<IconProps>;
    Vector41201327?: PrimitiveOverrideProps<IconProps>;
    Vector41201328?: PrimitiveOverrideProps<IconProps>;
    Vector41201329?: PrimitiveOverrideProps<IconProps>;
    "PhoneBlackIcon 2"?: PrimitiveOverrideProps<ViewProps>;
    Vector41201331?: PrimitiveOverrideProps<IconProps>;
    "forward_to_inbox_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector41201334?: PrimitiveOverrideProps<IconProps>;
    Vector41211324?: PrimitiveOverrideProps<IconProps>;
    "Group 416"?: PrimitiveOverrideProps<ViewProps>;
    Button39885044?: PrimitiveOverrideProps<ButtonProps>;
    Vector41201338?: PrimitiveOverrideProps<IconProps>;
    Vector41231383?: PrimitiveOverrideProps<IconProps>;
    "ChatIconBlack 3"?: PrimitiveOverrideProps<ViewProps>;
    Vector41231385?: PrimitiveOverrideProps<IconProps>;
    "SendIconBlack 2"?: PrimitiveOverrideProps<ViewProps>;
    Vector41231387?: PrimitiveOverrideProps<IconProps>;
    Compartilhar41231388?: PrimitiveOverrideProps<TextProps>;
    Comentar41231389?: PrimitiveOverrideProps<TextProps>;
    Gostei41231391?: PrimitiveOverrideProps<TextProps>;
    "Group 432"?: PrimitiveOverrideProps<ViewProps>;
    "Group 9441231394"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13041231395"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13141231396"?: PrimitiveOverrideProps<ViewProps>;
    Button41231397?: PrimitiveOverrideProps<ButtonProps>;
    Button41231398?: PrimitiveOverrideProps<ButtonProps>;
    "Suas Publica\u00E7\u00F5es41231399"?: PrimitiveOverrideProps<TextProps>;
    "Poxaaa, que pena :( No momento voc\u00EA n\u00E3o est\u00E1 participando de nenhuma vaga, busque vagas na aba \u201CVagas de emprego\u201D41231400"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 13441231401"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13841231402"?: PrimitiveOverrideProps<ViewProps>;
    ".41231403"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 13541231404"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 14141231405"?: PrimitiveOverrideProps<ViewProps>;
    "Publica\u00E7\u00F5es41231406"?: PrimitiveOverrideProps<TextProps>;
    Destaques41231407?: PrimitiveOverrideProps<TextProps>;
    "Jo\u00E3o Pedro Borges41231408"?: PrimitiveOverrideProps<TextProps>;
    "Jo\u00E3o Pedro Borges41231409"?: PrimitiveOverrideProps<TextProps>;
    "...41231410"?: PrimitiveOverrideProps<TextProps>;
    "...41231411"?: PrimitiveOverrideProps<TextProps>;
    "Voc\u00EA41231412"?: PrimitiveOverrideProps<TextProps>;
    "Voc\u00EA41231413"?: PrimitiveOverrideProps<TextProps>;
    ".41231414"?: PrimitiveOverrideProps<TextProps>;
    "AvatarPerfil 241231415"?: PrimitiveOverrideProps<ImageProps>;
    "AvatarPerfil 141231416"?: PrimitiveOverrideProps<ImageProps>;
    "Boa tarde amigos! Hoje tive a incr\u00EDvel oportunidade de visitar a sede da CityCorp, e posso dizer que essa experi\u00EAncia foi ...mais41231417"?: PrimitiveOverrideProps<TextProps>;
    image41231418?: PrimitiveOverrideProps<ImageProps>;
    image41231419?: PrimitiveOverrideProps<ImageProps>;
    image41231420?: PrimitiveOverrideProps<ImageProps>;
    image41231421?: PrimitiveOverrideProps<ImageProps>;
    image41231422?: PrimitiveOverrideProps<ImageProps>;
    "+ 441231423"?: PrimitiveOverrideProps<TextProps>;
    "4 min41231424"?: PrimitiveOverrideProps<TextProps>;
    "5 d41231425"?: PrimitiveOverrideProps<TextProps>;
    Vector41231426?: PrimitiveOverrideProps<IconProps>;
    "ChatIconBlack 4"?: PrimitiveOverrideProps<ViewProps>;
    Vector41231428?: PrimitiveOverrideProps<IconProps>;
    "SendIconBlack 3"?: PrimitiveOverrideProps<ViewProps>;
    Vector41231430?: PrimitiveOverrideProps<IconProps>;
    Compartilhar41231431?: PrimitiveOverrideProps<TextProps>;
    Comentar41231432?: PrimitiveOverrideProps<TextProps>;
    Gostei41231433?: PrimitiveOverrideProps<TextProps>;
} & EscapeHatchProps;
export declare type MeuPerfil2Props = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: MeuPerfil2OverridesProps | undefined | null;
}>;
export default function MeuPerfil2(props: MeuPerfil2Props): React.ReactElement;
