/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { BancoImagens } from "../models";
import { ButtonProps, IconProps, ImageProps, SelectFieldProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type MeuPerfil1OverridesProps = {
    MeuPerfil1?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 27"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 26"?: PrimitiveOverrideProps<ViewProps>;
    "Noise & Texture"?: PrimitiveOverrideProps<ImageProps>;
    "Group 422"?: PrimitiveOverrideProps<ViewProps>;
    "Group 408"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 122"?: PrimitiveOverrideProps<ViewProps>;
    "AvatarPerfil 141002017"?: PrimitiveOverrideProps<ImageProps>;
    "Ellipse 105"?: PrimitiveOverrideProps<IconProps>;
    "edit_24dp_5F6368_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39883286?: PrimitiveOverrideProps<IconProps>;
    "Jo\u00E3o Pedro Borges39883287"?: PrimitiveOverrideProps<TextProps>;
    "Group 404"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 12339883289"?: PrimitiveOverrideProps<ViewProps>;
    Status?: PrimitiveOverrideProps<TextProps>;
    SelectField?: PrimitiveOverrideProps<SelectFieldProps>;
    "Group 407"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 125"?: PrimitiveOverrideProps<ViewProps>;
    Button39883295?: PrimitiveOverrideProps<ButtonProps>;
    "forward_to_inbox_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39883297?: PrimitiveOverrideProps<IconProps>;
    Button39883298?: PrimitiveOverrideProps<ButtonProps>;
    "Acompanhe o preenchimento de seu curr\u00EDculo aqui!"?: PrimitiveOverrideProps<TextProps>;
    "Curr\u00EDculo"?: PrimitiveOverrideProps<TextProps>;
    Send?: PrimitiveOverrideProps<ViewProps>;
    "attach_email_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector41211337?: PrimitiveOverrideProps<IconProps>;
    "Voc\u00EA est\u00E1 quase l\u00E1, falta pouco para o seu curr\u00EDculo ficar pronto!"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 127"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 142"?: PrimitiveOverrideProps<ViewProps>;
    "60%"?: PrimitiveOverrideProps<TextProps>;
    "Group 406"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 126"?: PrimitiveOverrideProps<ViewProps>;
    "Escolaridade / Forma\u00E7\u00E3o"?: PrimitiveOverrideProps<TextProps>;
    "Curso:"?: PrimitiveOverrideProps<TextProps>;
    "Per\u00EDodo do Curso:"?: PrimitiveOverrideProps<TextProps>;
    "Ano / Semestre:"?: PrimitiveOverrideProps<TextProps>;
    "Fatec Ferraz de Vasconcelos"?: PrimitiveOverrideProps<TextProps>;
    "ADS - An\u00E1lise e Desenvolvimento de Sistemas"?: PrimitiveOverrideProps<TextProps>;
    Vespertino?: PrimitiveOverrideProps<TextProps>;
    "2\u00B0 Semestre"?: PrimitiveOverrideProps<TextProps>;
    Vector41211330?: PrimitiveOverrideProps<IconProps>;
    "Institui\u00E7\u00E3o de Ensino:"?: PrimitiveOverrideProps<TextProps>;
    "Group 405"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 12339883321"?: PrimitiveOverrideProps<ViewProps>;
    "Telefone: (11) 91234-6789"?: PrimitiveOverrideProps<TextProps>;
    "E-mail: joaoborges.2010@gmail.com"?: PrimitiveOverrideProps<TextProps>;
    "N\u00EDvel da Condi\u00E7\u00E3o: N\u00EDvel 2"?: PrimitiveOverrideProps<TextProps>;
    "Informa\u00E7\u00F5es do Usu\u00E1rio"?: PrimitiveOverrideProps<TextProps>;
    "Sobre Mim:"?: PrimitiveOverrideProps<TextProps>;
    "PuzzleBlackIcon 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector41121468?: PrimitiveOverrideProps<IconProps>;
    "Line 52"?: PrimitiveOverrideProps<IconProps>;
    Vector41121470?: PrimitiveOverrideProps<IconProps>;
    Vector41121475?: PrimitiveOverrideProps<IconProps>;
    "Sou Jo\u00E3o, desenvolvedor front-end apaixonado por tecnologia e sempre em busca de aprender. Gosto de resolver problemas e criar interfaces funcionais e bonitas. Busco oportunidades em empresas inclusivas onde eu possa crescer e fazer a diferen\u00E7a com meu trabalho."?: PrimitiveOverrideProps<TextProps>;
    Vector39883333?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 19"?: PrimitiveOverrideProps<ViewProps>;
    "Group 431"?: PrimitiveOverrideProps<ViewProps>;
    Vector41051360?: PrimitiveOverrideProps<IconProps>;
    Vector41051361?: PrimitiveOverrideProps<IconProps>;
    Vector41051362?: PrimitiveOverrideProps<IconProps>;
    Ajuda?: PrimitiveOverrideProps<TextProps>;
    Vector41051364?: PrimitiveOverrideProps<IconProps>;
    "logo_branca_conecta 1"?: PrimitiveOverrideProps<ImageProps>;
    "+ 439883339"?: PrimitiveOverrideProps<TextProps>;
    "Line 28"?: PrimitiveOverrideProps<IconProps>;
    "Group 95"?: PrimitiveOverrideProps<ViewProps>;
    "Group 94"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 130"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131"?: PrimitiveOverrideProps<ViewProps>;
    Button39883345?: PrimitiveOverrideProps<ButtonProps>;
    Button39883346?: PrimitiveOverrideProps<ButtonProps>;
    "Suas Publica\u00E7\u00F5es"?: PrimitiveOverrideProps<TextProps>;
    "Poxaaa, que pena :( No momento voc\u00EA n\u00E3o est\u00E1 participando de nenhuma vaga, busque vagas na aba \u201CVagas de emprego\u201D"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 134"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 138"?: PrimitiveOverrideProps<ViewProps>;
    ".39883351"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 135"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 141"?: PrimitiveOverrideProps<ViewProps>;
    "Publica\u00E7\u00F5es"?: PrimitiveOverrideProps<TextProps>;
    Destaques?: PrimitiveOverrideProps<TextProps>;
    "Jo\u00E3o Pedro Borges39883356"?: PrimitiveOverrideProps<TextProps>;
    "Jo\u00E3o Pedro Borges39883357"?: PrimitiveOverrideProps<TextProps>;
    "...39883358"?: PrimitiveOverrideProps<TextProps>;
    "...39883359"?: PrimitiveOverrideProps<TextProps>;
    "Voc\u00EA39883360"?: PrimitiveOverrideProps<TextProps>;
    "Voc\u00EA39883361"?: PrimitiveOverrideProps<TextProps>;
    ".39883362"?: PrimitiveOverrideProps<TextProps>;
    image39883363?: PrimitiveOverrideProps<IconProps>;
    "AvatarPerfil 141042422"?: PrimitiveOverrideProps<ImageProps>;
    "Boa tarde amigos! Hoje tive a incr\u00EDvel oportunidade de visitar a sede da CityCorp, e posso dizer que essa experi\u00EAncia foi ...mais"?: PrimitiveOverrideProps<TextProps>;
    image39883368?: PrimitiveOverrideProps<ImageProps>;
    image39883369?: PrimitiveOverrideProps<ImageProps>;
    image39883370?: PrimitiveOverrideProps<ImageProps>;
    image39883371?: PrimitiveOverrideProps<ImageProps>;
    image39883372?: PrimitiveOverrideProps<ImageProps>;
    "+ 439883373"?: PrimitiveOverrideProps<TextProps>;
    "4 min"?: PrimitiveOverrideProps<TextProps>;
    "5 d"?: PrimitiveOverrideProps<TextProps>;
    "Jo\u00E3o Pedro Borges39883388"?: PrimitiveOverrideProps<TextProps>;
    "Group 425"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 160"?: PrimitiveOverrideProps<ViewProps>;
    "Upload de curr\u00EDculos"?: PrimitiveOverrideProps<TextProps>;
    Upload?: PrimitiveOverrideProps<TextProps>;
    x?: PrimitiveOverrideProps<TextProps>;
    "Line 38"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 161"?: PrimitiveOverrideProps<ViewProps>;
    "Formatos permitidos: PDF, Doc, Docx | Tamanho M\u00E1ximo 5.0MB"?: PrimitiveOverrideProps<TextProps>;
    Button39883397?: PrimitiveOverrideProps<ButtonProps>;
    Button39883398?: PrimitiveOverrideProps<ButtonProps>;
    "PhoneBlackIcon 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector41121473?: PrimitiveOverrideProps<IconProps>;
    "AvatarPerfil 14043872"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 20"?: PrimitiveOverrideProps<ViewProps>;
    Button41021083?: PrimitiveOverrideProps<ButtonProps>;
    Button41021084?: PrimitiveOverrideProps<ButtonProps>;
    Button41021085?: PrimitiveOverrideProps<ButtonProps>;
    Vector41201353?: PrimitiveOverrideProps<IconProps>;
    "ChatIconBlack 2"?: PrimitiveOverrideProps<ViewProps>;
    Vector41201355?: PrimitiveOverrideProps<IconProps>;
    "SendIconBlack 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector41201357?: PrimitiveOverrideProps<IconProps>;
    Compartilhar?: PrimitiveOverrideProps<TextProps>;
    Gostei?: PrimitiveOverrideProps<TextProps>;
    Comentar?: PrimitiveOverrideProps<TextProps>;
} & EscapeHatchProps;
export declare type MeuPerfil1Props = React.PropsWithChildren<Partial<ViewProps> & {
    bancoImagens?: BancoImagens;
} & {
    overrides?: MeuPerfil1OverridesProps | undefined | null;
}>;
export default function MeuPerfil1(props: MeuPerfil1Props): React.ReactElement;
