/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { ButtonProps, FlexProps, IconProps, ImageProps, SelectFieldProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type MeuPerfilOverridesProps = {
    MeuPerfil?: PrimitiveOverrideProps<ViewProps>;
    NavBarHeaderConecta?: PrimitiveOverrideProps<FlexProps>;
    "Frame 3214387826"?: PrimitiveOverrideProps<FlexProps>;
    Vector4387827?: PrimitiveOverrideProps<IconProps>;
    Vector4387828?: PrimitiveOverrideProps<IconProps>;
    Vector4387829?: PrimitiveOverrideProps<IconProps>;
    Vector4387830?: PrimitiveOverrideProps<IconProps>;
    "Frame 322"?: PrimitiveOverrideProps<FlexProps>;
    "logo_branca_conecta 2"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 3214387833"?: PrimitiveOverrideProps<FlexProps>;
    Button4387834?: PrimitiveOverrideProps<ButtonProps>;
    Button4387835?: PrimitiveOverrideProps<ButtonProps>;
    "Fundo Novo"?: PrimitiveOverrideProps<ImageProps>;
    "Group 408"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 122"?: PrimitiveOverrideProps<ViewProps>;
    "AvatarPerfil 141002006"?: PrimitiveOverrideProps<ImageProps>;
    "Ellipse 105"?: PrimitiveOverrideProps<IconProps>;
    "edit_24dp_5F6368_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882924?: PrimitiveOverrideProps<IconProps>;
    "Jo\u00E3o Pedro Borges39882925"?: PrimitiveOverrideProps<TextProps>;
    "Group 404"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 12339882927"?: PrimitiveOverrideProps<ViewProps>;
    Status?: PrimitiveOverrideProps<TextProps>;
    SelectField?: PrimitiveOverrideProps<SelectFieldProps>;
    "Group 407"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 125"?: PrimitiveOverrideProps<ViewProps>;
    "Acompanhe o preenchimento de seu curr\u00EDculo aqui!"?: PrimitiveOverrideProps<TextProps>;
    "Curr\u00EDculo"?: PrimitiveOverrideProps<TextProps>;
    Smiling?: PrimitiveOverrideProps<ViewProps>;
    "Voc\u00EA est\u00E1 quase l\u00E1, falta pouco para o seu curr\u00EDculo ficar pronto!"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 127"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 142"?: PrimitiveOverrideProps<ViewProps>;
    "60%"?: PrimitiveOverrideProps<TextProps>;
    "Group 406"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 126"?: PrimitiveOverrideProps<ViewProps>;
    "Escolaridade / Forma\u00E7\u00E3o"?: PrimitiveOverrideProps<TextProps>;
    "Curso:"?: PrimitiveOverrideProps<TextProps>;
    "Per\u00EDodo do Curso:"?: PrimitiveOverrideProps<TextProps>;
    "Ano / Semestre:"?: PrimitiveOverrideProps<TextProps>;
    "Fatec Ferraz de Vasconcelos"?: PrimitiveOverrideProps<TextProps>;
    "ADS - An\u00E1lise e Desenvolvimento de Sistemas"?: PrimitiveOverrideProps<TextProps>;
    Vespertino?: PrimitiveOverrideProps<TextProps>;
    "2\u00B0 Semestre"?: PrimitiveOverrideProps<TextProps>;
    "book_2_24dp_000000_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882953?: PrimitiveOverrideProps<IconProps>;
    "Institui\u00E7\u00E3o de Ensino:"?: PrimitiveOverrideProps<TextProps>;
    "Group 405"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 12339882956"?: PrimitiveOverrideProps<ViewProps>;
    "Telefone: (11) 91234-6789"?: PrimitiveOverrideProps<TextProps>;
    "E-mail: joaoborges.2010@gmail.com"?: PrimitiveOverrideProps<TextProps>;
    "N\u00EDvel da Condi\u00E7\u00E3o: N\u00EDvel 2"?: PrimitiveOverrideProps<TextProps>;
    "Informa\u00E7\u00F5es do Usu\u00E1rio"?: PrimitiveOverrideProps<TextProps>;
    "Sobre Mim:"?: PrimitiveOverrideProps<TextProps>;
    "Line 52"?: PrimitiveOverrideProps<IconProps>;
    "Male User"?: PrimitiveOverrideProps<ViewProps>;
    "person_24dp_5F6368_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    "ProfileIconBlack 141121464"?: PrimitiveOverrideProps<ViewProps>;
    Vector41121465?: PrimitiveOverrideProps<IconProps>;
    "Sou Jo\u00E3o, desenvolvedor front-end, apaixonado por tecnologia e sempre em busca de aprender. Gosto de resolver problemas e criar interfaces funcionais e bonitas. Busco oportunidades em empresas inclusivas onde eu possa crescer e fazer a diferen\u00E7a com meu trabalho e conhecimentos."?: PrimitiveOverrideProps<TextProps>;
    "ProfileIconBlack 141121461"?: PrimitiveOverrideProps<ViewProps>;
    Vector41121462?: PrimitiveOverrideProps<IconProps>;
    "+ 439882978"?: PrimitiveOverrideProps<TextProps>;
    "Line 28"?: PrimitiveOverrideProps<IconProps>;
    "Group 95"?: PrimitiveOverrideProps<ViewProps>;
    "Group 94"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 130"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131"?: PrimitiveOverrideProps<ViewProps>;
    Button39882984?: PrimitiveOverrideProps<ButtonProps>;
    Button39882985?: PrimitiveOverrideProps<ButtonProps>;
    "Suas Publica\u00E7\u00F5es"?: PrimitiveOverrideProps<TextProps>;
    "Poxaaa, que pena :( No momento voc\u00EA n\u00E3o est\u00E1 participando de nenhuma vaga, busque vagas na aba \u201CVagas de emprego\u201D"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 134"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 138"?: PrimitiveOverrideProps<ViewProps>;
    ".39882990"?: PrimitiveOverrideProps<TextProps>;
    Button39882991?: PrimitiveOverrideProps<ButtonProps>;
    Button39882992?: PrimitiveOverrideProps<ButtonProps>;
    "Jo\u00E3o Pedro Borges39882993"?: PrimitiveOverrideProps<TextProps>;
    "Jo\u00E3o Pedro Borges39882994"?: PrimitiveOverrideProps<TextProps>;
    "...39882995"?: PrimitiveOverrideProps<TextProps>;
    "...39882996"?: PrimitiveOverrideProps<TextProps>;
    "Voc\u00EA39882997"?: PrimitiveOverrideProps<TextProps>;
    "Voc\u00EA39882998"?: PrimitiveOverrideProps<TextProps>;
    ".39882999"?: PrimitiveOverrideProps<TextProps>;
    "AvatarPerfil 141042416"?: PrimitiveOverrideProps<ImageProps>;
    "AvatarPerfil 3"?: PrimitiveOverrideProps<ImageProps>;
    "Boa tarde amigos! Hoje tive a incr\u00EDvel oportunidade de visitar a sede da CityCorp, e posso dizer que essa experi\u00EAncia foi ...mais"?: PrimitiveOverrideProps<TextProps>;
    image39883005?: PrimitiveOverrideProps<ImageProps>;
    image39883006?: PrimitiveOverrideProps<ImageProps>;
    image39883007?: PrimitiveOverrideProps<ImageProps>;
    image39883008?: PrimitiveOverrideProps<ImageProps>;
    image39883009?: PrimitiveOverrideProps<ImageProps>;
    "+ 439883010"?: PrimitiveOverrideProps<TextProps>;
    "Group 65"?: PrimitiveOverrideProps<ViewProps>;
    "Group 66"?: PrimitiveOverrideProps<ViewProps>;
    Gostei?: PrimitiveOverrideProps<TextProps>;
    Comentar?: PrimitiveOverrideProps<TextProps>;
    Compartilhar?: PrimitiveOverrideProps<TextProps>;
    "LikeIconBlack 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector41211347?: PrimitiveOverrideProps<IconProps>;
    "SendIconBlack 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector41211342?: PrimitiveOverrideProps<IconProps>;
    "4 min"?: PrimitiveOverrideProps<TextProps>;
    "5 d"?: PrimitiveOverrideProps<TextProps>;
    "PhoneBlackIcon 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector41121447?: PrimitiveOverrideProps<IconProps>;
    "MailBlackIcon 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector41121452?: PrimitiveOverrideProps<IconProps>;
    "PuzzleBlackIcon 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector41121457?: PrimitiveOverrideProps<IconProps>;
    "forward_to_inbox_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    "attach_email_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39883035?: PrimitiveOverrideProps<IconProps>;
    "AvatarPerfil 14043871"?: PrimitiveOverrideProps<ImageProps>;
    "ChatIconBlack 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector41211350?: PrimitiveOverrideProps<IconProps>;
    Button41231372?: PrimitiveOverrideProps<ButtonProps>;
    Button41231373?: PrimitiveOverrideProps<ButtonProps>;
    Vector39883033?: PrimitiveOverrideProps<IconProps>;
    Vector41231381?: PrimitiveOverrideProps<IconProps>;
    NavBarMenu?: PrimitiveOverrideProps<FlexProps>;
    "Frame 3214387845"?: PrimitiveOverrideProps<FlexProps>;
    Button4387846?: PrimitiveOverrideProps<ButtonProps>;
    Button4387847?: PrimitiveOverrideProps<ButtonProps>;
    Button4387848?: PrimitiveOverrideProps<ButtonProps>;
} & EscapeHatchProps;
export declare type MeuPerfilProps = React.PropsWithChildren<Partial<ViewProps> & {
    bancoImagens?: any;
} & {
    overrides?: MeuPerfilOverridesProps | undefined | null;
}>;
export default function MeuPerfil(props: MeuPerfilProps): React.ReactElement;
