/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { ButtonProps, FlexProps, IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type MeuPerfilOverridesProps = {
    MeuPerfil?: PrimitiveOverrideProps<ViewProps>;
    "Fundo Novo"?: PrimitiveOverrideProps<ImageProps>;
    "Group 408"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 122"?: PrimitiveOverrideProps<ViewProps>;
    "AvatarPerfil 138511818"?: PrimitiveOverrideProps<ImageProps>;
    "Ellipse 105"?: PrimitiveOverrideProps<IconProps>;
    "edit_24dp_5F6368_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector38511821?: PrimitiveOverrideProps<IconProps>;
    "Jo\u00E3o Pedro Borges38511822"?: PrimitiveOverrideProps<TextProps>;
    "Group 404"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 12338511824"?: PrimitiveOverrideProps<ViewProps>;
    Status?: PrimitiveOverrideProps<TextProps>;
    SelectField?: PrimitiveOverrideProps<FlexProps>;
    "Group 407"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 125"?: PrimitiveOverrideProps<ViewProps>;
    "Acompanhe o preenchimento de seu curr\u00EDculo aqui!"?: PrimitiveOverrideProps<TextProps>;
    "Curr\u00EDculo"?: PrimitiveOverrideProps<TextProps>;
    Smiling?: PrimitiveOverrideProps<ViewProps>;
    "Voc\u00EA est\u00E1 quase l\u00E1, falta pouco para o seu curr\u00EDculo ficar pronto!"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 127"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 142"?: PrimitiveOverrideProps<ViewProps>;
    "60%"?: PrimitiveOverrideProps<TextProps>;
    "Group 406"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 126"?: PrimitiveOverrideProps<ViewProps>;
    "Escolaridade / Forma\u00E7\u00E3o"?: PrimitiveOverrideProps<TextProps>;
    "Curso:"?: PrimitiveOverrideProps<TextProps>;
    "Per\u00EDodo do Curso:"?: PrimitiveOverrideProps<TextProps>;
    "Ano / Semestre:"?: PrimitiveOverrideProps<TextProps>;
    "Fatec Ferraz de Vasconcelos"?: PrimitiveOverrideProps<TextProps>;
    "ADS - An\u00E1lise e Desenvolvimento de Sistemas"?: PrimitiveOverrideProps<TextProps>;
    Vespertino?: PrimitiveOverrideProps<TextProps>;
    "2\u00B0 Semestre"?: PrimitiveOverrideProps<TextProps>;
    "book_2_24dp_000000_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector38511847?: PrimitiveOverrideProps<IconProps>;
    "Institui\u00E7\u00E3o de Ensino:"?: PrimitiveOverrideProps<TextProps>;
    "Group 405"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 12338511850"?: PrimitiveOverrideProps<ViewProps>;
    "Telefone: (11) 91234-6789"?: PrimitiveOverrideProps<TextProps>;
    "E-mail: joaoborges.2010@gmail.com"?: PrimitiveOverrideProps<TextProps>;
    "N\u00EDvel da Condi\u00E7\u00E3o: N\u00EDvel 2"?: PrimitiveOverrideProps<TextProps>;
    "Informa\u00E7\u00F5es do Usu\u00E1rio"?: PrimitiveOverrideProps<TextProps>;
    "Sobre Mim:"?: PrimitiveOverrideProps<TextProps>;
    "Line 52"?: PrimitiveOverrideProps<IconProps>;
    "Male User"?: PrimitiveOverrideProps<ViewProps>;
    "person_24dp_5F6368_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    "ProfileIconBlack 138511859"?: PrimitiveOverrideProps<ViewProps>;
    Vector38511860?: PrimitiveOverrideProps<IconProps>;
    "Sou Jo\u00E3o, desenvolvedor front-end, apaixonado por tecnologia e sempre em busca de aprender. Gosto de resolver problemas e criar interfaces funcionais e bonitas. Busco oportunidades em empresas inclusivas onde eu possa crescer e fazer a diferen\u00E7a com meu trabalho e conhecimentos."?: PrimitiveOverrideProps<TextProps>;
    "ProfileIconBlack 138511862"?: PrimitiveOverrideProps<ViewProps>;
    Vector38511863?: PrimitiveOverrideProps<IconProps>;
    "PhoneBlackIcon 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector38511907?: PrimitiveOverrideProps<IconProps>;
    "MailBlackIcon 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector38511909?: PrimitiveOverrideProps<IconProps>;
    "PuzzleBlackIcon 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector38511911?: PrimitiveOverrideProps<IconProps>;
    "forward_to_inbox_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    "attach_email_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector38511914?: PrimitiveOverrideProps<IconProps>;
    "AvatarPerfil 138511915"?: PrimitiveOverrideProps<ImageProps>;
    Vector38511916?: PrimitiveOverrideProps<IconProps>;
    Vector38511917?: PrimitiveOverrideProps<IconProps>;
    Button38511918?: PrimitiveOverrideProps<FlexProps>;
    Button38511919?: PrimitiveOverrideProps<FlexProps>;
    NavBarHeaderConecta?: PrimitiveOverrideProps<FlexProps>;
    "Frame 322"?: PrimitiveOverrideProps<FlexProps>;
    "logo_branca_conecta 2"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 321"?: PrimitiveOverrideProps<FlexProps>;
    Vector38464880?: PrimitiveOverrideProps<IconProps>;
    Vector38464881?: PrimitiveOverrideProps<IconProps>;
    Vector38464882?: PrimitiveOverrideProps<IconProps>;
    Vector38464883?: PrimitiveOverrideProps<IconProps>;
    "Group 483"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 134"?: PrimitiveOverrideProps<ViewProps>;
    "+ 438511864"?: PrimitiveOverrideProps<TextProps>;
    "Line 28"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 131"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 138"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 139"?: PrimitiveOverrideProps<ViewProps>;
    ".38511875"?: PrimitiveOverrideProps<TextProps>;
    "Jo\u00E3o Pedro Borges38511878"?: PrimitiveOverrideProps<TextProps>;
    "Jo\u00E3o Pedro Borges38511879"?: PrimitiveOverrideProps<TextProps>;
    "...38511880"?: PrimitiveOverrideProps<TextProps>;
    "...38511881"?: PrimitiveOverrideProps<TextProps>;
    "Voc\u00EA38511882"?: PrimitiveOverrideProps<TextProps>;
    "Voc\u00EA38511883"?: PrimitiveOverrideProps<TextProps>;
    ".38511884"?: PrimitiveOverrideProps<TextProps>;
    "AvatarPerfil 138511885"?: PrimitiveOverrideProps<ImageProps>;
    "AvatarPerfil 3"?: PrimitiveOverrideProps<ImageProps>;
    "Boa tarde amigos! Hoje tive a incr\u00EDvel oportunidade de visitar a sede da CityCorp, e posso dizer que essa experi\u00EAncia foi ...mais"?: PrimitiveOverrideProps<TextProps>;
    "Suas Publica\u00E7\u00F5es"?: PrimitiveOverrideProps<TextProps>;
    image38511888?: PrimitiveOverrideProps<ImageProps>;
    image38511889?: PrimitiveOverrideProps<ImageProps>;
    image38511890?: PrimitiveOverrideProps<ImageProps>;
    image38511891?: PrimitiveOverrideProps<ImageProps>;
    image38511892?: PrimitiveOverrideProps<ImageProps>;
    "+ 438511893"?: PrimitiveOverrideProps<TextProps>;
    "Group 65"?: PrimitiveOverrideProps<ViewProps>;
    "Group 66"?: PrimitiveOverrideProps<ViewProps>;
    Gostei?: PrimitiveOverrideProps<TextProps>;
    Comentar?: PrimitiveOverrideProps<TextProps>;
    Compartilhar?: PrimitiveOverrideProps<TextProps>;
    "LikeIconBlack 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector38511900?: PrimitiveOverrideProps<IconProps>;
    "SendIconBlack 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector38511902?: PrimitiveOverrideProps<IconProps>;
    "4 min"?: PrimitiveOverrideProps<TextProps>;
    "5 d"?: PrimitiveOverrideProps<TextProps>;
    Vector38511905?: PrimitiveOverrideProps<IconProps>;
    Button38531310?: PrimitiveOverrideProps<ButtonProps>;
    Button38531311?: PrimitiveOverrideProps<ButtonProps>;
} & EscapeHatchProps;
export declare type MeuPerfilProps = React.PropsWithChildren<Partial<ViewProps> & {
    bancoImagens?: any;
} & {
    overrides?: MeuPerfilOverridesProps | undefined | null;
}>;
export default function MeuPerfil(props: MeuPerfilProps): React.ReactElement;
