/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { ButtonProps, IconProps, ImageProps, SelectFieldProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type MeuPerfil5OverridesProps = {
    MeuPerfil5?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 27"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 26"?: PrimitiveOverrideProps<ViewProps>;
    "Noise & Texture"?: PrimitiveOverrideProps<ImageProps>;
    "DALL\u00B7E 2024-11-02 01.57.03 - A softer abstract background with a pattern of faceted polygons in calming colors such as soft blues, greens, purples, and muted yellows. The shapes s 1"?: PrimitiveOverrideProps<ImageProps>;
    "Group 408"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 122"?: PrimitiveOverrideProps<ViewProps>;
    "AvatarPerfil 241002070"?: PrimitiveOverrideProps<ImageProps>;
    "Ellipse 105"?: PrimitiveOverrideProps<IconProps>;
    "edit_24dp_5F6368_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882814?: PrimitiveOverrideProps<IconProps>;
    "Jo\u00E3o Pedro Borges39882815"?: PrimitiveOverrideProps<TextProps>;
    "Group 404"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 12339882817"?: PrimitiveOverrideProps<ViewProps>;
    Status?: PrimitiveOverrideProps<TextProps>;
    SelectField?: PrimitiveOverrideProps<SelectFieldProps>;
    "Group 407"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 125"?: PrimitiveOverrideProps<ViewProps>;
    "Acompanhe o preenchimento de seu curr\u00EDculo aqui!"?: PrimitiveOverrideProps<TextProps>;
    Button39882824?: PrimitiveOverrideProps<ButtonProps>;
    Button39882825?: PrimitiveOverrideProps<ButtonProps>;
    "Curr\u00EDculo"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 127"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 142"?: PrimitiveOverrideProps<ViewProps>;
    Send?: PrimitiveOverrideProps<ViewProps>;
    "100%"?: PrimitiveOverrideProps<TextProps>;
    "Group 406"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 126"?: PrimitiveOverrideProps<ViewProps>;
    "Escolaridade / Forma\u00E7\u00E3o"?: PrimitiveOverrideProps<TextProps>;
    "Curso:"?: PrimitiveOverrideProps<TextProps>;
    "Per\u00EDodo do Curso:"?: PrimitiveOverrideProps<TextProps>;
    "Ano / Semestre:"?: PrimitiveOverrideProps<TextProps>;
    "Fatec Ferraz de Vasconcelos"?: PrimitiveOverrideProps<TextProps>;
    "ADS - An\u00E1lise e Desenvolvimento de Sistemas"?: PrimitiveOverrideProps<TextProps>;
    Vespertino?: PrimitiveOverrideProps<TextProps>;
    "2\u00B0 Semestre"?: PrimitiveOverrideProps<TextProps>;
    Vector41211326?: PrimitiveOverrideProps<IconProps>;
    "Institui\u00E7\u00E3o de Ensino:"?: PrimitiveOverrideProps<TextProps>;
    "Group 405"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 12339882846"?: PrimitiveOverrideProps<ViewProps>;
    "Telefone: (11) 91234-6789"?: PrimitiveOverrideProps<TextProps>;
    "E-mail: joaoborges.2010@gmail.com"?: PrimitiveOverrideProps<TextProps>;
    "N\u00EDvel da Condi\u00E7\u00E3o: N\u00EDvel 2"?: PrimitiveOverrideProps<TextProps>;
    "Informa\u00E7\u00F5es do Usu\u00E1rio"?: PrimitiveOverrideProps<TextProps>;
    "Sobre Mim:"?: PrimitiveOverrideProps<TextProps>;
    "PuzzleBlackIcon 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector41162131?: PrimitiveOverrideProps<IconProps>;
    "Line 52"?: PrimitiveOverrideProps<IconProps>;
    "PhoneBlackIcon 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector41162126?: PrimitiveOverrideProps<IconProps>;
    Vector41162128?: PrimitiveOverrideProps<IconProps>;
    "Male User"?: PrimitiveOverrideProps<ImageProps>;
    Vector41162133?: PrimitiveOverrideProps<IconProps>;
    "Sou Jo\u00E3o, desenvolvedor front-end apaixonado por tecnologia e sempre em busca de aprender. Gosto de resolver problemas e criar interfaces funcionais e bonitas. Busco oportunidades em empresas inclusivas onde eu possa crescer e fazer a diferen\u00E7a com meu trabalho."?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 19"?: PrimitiveOverrideProps<ViewProps>;
    "Group 431"?: PrimitiveOverrideProps<ViewProps>;
    Vector41051381?: PrimitiveOverrideProps<IconProps>;
    Vector41051382?: PrimitiveOverrideProps<IconProps>;
    Vector41051383?: PrimitiveOverrideProps<IconProps>;
    Ajuda?: PrimitiveOverrideProps<TextProps>;
    Vector41051385?: PrimitiveOverrideProps<IconProps>;
    "logo_branca_conecta 1"?: PrimitiveOverrideProps<ImageProps>;
    "+ 439882865"?: PrimitiveOverrideProps<TextProps>;
    "Line 28"?: PrimitiveOverrideProps<IconProps>;
    "Group 95"?: PrimitiveOverrideProps<ViewProps>;
    "Group 94"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 130"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 131"?: PrimitiveOverrideProps<ViewProps>;
    Button39882871?: PrimitiveOverrideProps<ButtonProps>;
    Button39882872?: PrimitiveOverrideProps<ButtonProps>;
    "Suas Publica\u00E7\u00F5es"?: PrimitiveOverrideProps<TextProps>;
    "Poxaaa, que pena :( No momento voc\u00EA n\u00E3o est\u00E1 participando de nenhuma vaga, busque vagas na aba \u201CVagas de emprego\u201D"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 134"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 138"?: PrimitiveOverrideProps<ViewProps>;
    ".39882877"?: PrimitiveOverrideProps<TextProps>;
    Button39882878?: PrimitiveOverrideProps<ButtonProps>;
    Button39882879?: PrimitiveOverrideProps<ButtonProps>;
    Text?: PrimitiveOverrideProps<TextProps>;
    "Jo\u00E3o Pedro Borges39882881"?: PrimitiveOverrideProps<TextProps>;
    "Jo\u00E3o Pedro Borges39882882"?: PrimitiveOverrideProps<TextProps>;
    "...39882883"?: PrimitiveOverrideProps<TextProps>;
    "...39882884"?: PrimitiveOverrideProps<TextProps>;
    "Voc\u00EA39882885"?: PrimitiveOverrideProps<TextProps>;
    "Voc\u00EA39882886"?: PrimitiveOverrideProps<TextProps>;
    ".39882887"?: PrimitiveOverrideProps<TextProps>;
    "AvatarPerfil 141042428"?: PrimitiveOverrideProps<ImageProps>;
    "AvatarPerfil 241042430"?: PrimitiveOverrideProps<ImageProps>;
    "Boa tarde amigos! Hoje tive a incr\u00EDvel oportunidade de visitar a sede da CityCorp, e posso dizer que essa experi\u00EAncia foi ...mais"?: PrimitiveOverrideProps<TextProps>;
    image39882893?: PrimitiveOverrideProps<ImageProps>;
    image39882894?: PrimitiveOverrideProps<ImageProps>;
    image39882895?: PrimitiveOverrideProps<ImageProps>;
    image39882896?: PrimitiveOverrideProps<ImageProps>;
    image39882897?: PrimitiveOverrideProps<ImageProps>;
    "+ 439882898"?: PrimitiveOverrideProps<TextProps>;
    "4 min"?: PrimitiveOverrideProps<TextProps>;
    "5 d"?: PrimitiveOverrideProps<TextProps>;
    "Jo\u00E3o Pedro Borges39882913"?: PrimitiveOverrideProps<TextProps>;
    "Uhuuull!! Seu curr\u00EDculo est\u00E1 completo, boa."?: PrimitiveOverrideProps<TextProps>;
    "AvatarPerfil 14041867"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 21"?: PrimitiveOverrideProps<ViewProps>;
    Button41021056?: PrimitiveOverrideProps<ButtonProps>;
    Button41021057?: PrimitiveOverrideProps<ButtonProps>;
    Button41021058?: PrimitiveOverrideProps<ButtonProps>;
    Vector41201350?: PrimitiveOverrideProps<IconProps>;
    Vector41201351?: PrimitiveOverrideProps<IconProps>;
    Vector41231441?: PrimitiveOverrideProps<IconProps>;
    "ChatIconBlack 5"?: PrimitiveOverrideProps<ViewProps>;
    Vector41231443?: PrimitiveOverrideProps<IconProps>;
    "SendIconBlack 4"?: PrimitiveOverrideProps<ViewProps>;
    Vector41231445?: PrimitiveOverrideProps<IconProps>;
    Compartilhar?: PrimitiveOverrideProps<TextProps>;
    Comentar?: PrimitiveOverrideProps<TextProps>;
    Gostei?: PrimitiveOverrideProps<TextProps>;
} & EscapeHatchProps;
export declare type MeuPerfil5Props = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: MeuPerfil5OverridesProps | undefined | null;
}>;
export default function MeuPerfil5(props: MeuPerfil5Props): React.ReactElement;
