/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { ButtonProps, IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type Vagas4OverridesProps = {
    Vagas4?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 27"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 26"?: PrimitiveOverrideProps<ViewProps>;
    "Noise & Texture"?: PrimitiveOverrideProps<ImageProps>;
    "DALL\u00B7E 2024-11-02 01.57.03 - A softer abstract background with a pattern of faceted polygons in calming colors such as soft blues, greens, purples, and muted yellows. The shapes s 1"?: PrimitiveOverrideProps<ImageProps>;
    Empresa39882702?: PrimitiveOverrideProps<TextProps>;
    "Group 396"?: PrimitiveOverrideProps<ViewProps>;
    "Outras vagas semelhantes"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 15339882705"?: PrimitiveOverrideProps<ViewProps>;
    "DESIGN GR\u00C1FICO"?: PrimitiveOverrideProps<TextProps>;
    "4,1"?: PrimitiveOverrideProps<TextProps>;
    "star_24dp_000000_FILL0_wght400_GRAD0_opsz24 139882708"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882709?: PrimitiveOverrideProps<IconProps>;
    "New Berg"?: PrimitiveOverrideProps<TextProps>;
    "new_releases_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 2"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882712?: PrimitiveOverrideProps<IconProps>;
    "S\u00E3o Paulo - SP39882713"?: PrimitiveOverrideProps<TextProps>;
    "09 out"?: PrimitiveOverrideProps<TextProps>;
    Remoto?: PrimitiveOverrideProps<TextProps>;
    Vector40701074?: PrimitiveOverrideProps<IconProps>;
    "Line 3539882717"?: PrimitiveOverrideProps<IconProps>;
    Button39882718?: PrimitiveOverrideProps<ButtonProps>;
    Button39882719?: PrimitiveOverrideProps<ButtonProps>;
    Button39882720?: PrimitiveOverrideProps<ButtonProps>;
    "Rectangle 15339882721"?: PrimitiveOverrideProps<ViewProps>;
    "SEGURAN\u00C7A DA INFORMA\u00C7\u00C3O"?: PrimitiveOverrideProps<TextProps>;
    "4,9"?: PrimitiveOverrideProps<TextProps>;
    "star_24dp_000000_FILL0_wght400_GRAD0_opsz24 239882724"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882725?: PrimitiveOverrideProps<IconProps>;
    "City Corp"?: PrimitiveOverrideProps<TextProps>;
    "new_releases_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 139882727"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882728?: PrimitiveOverrideProps<IconProps>;
    "S\u00E3o Paulo - SP39882729"?: PrimitiveOverrideProps<TextProps>;
    "01 set"?: PrimitiveOverrideProps<TextProps>;
    "H\u00EDbrido39882731"?: PrimitiveOverrideProps<TextProps>;
    Vector40701070?: PrimitiveOverrideProps<IconProps>;
    "Line 3539882733"?: PrimitiveOverrideProps<IconProps>;
    Button39882734?: PrimitiveOverrideProps<ButtonProps>;
    Button39882735?: PrimitiveOverrideProps<ButtonProps>;
    Button39882736?: PrimitiveOverrideProps<ButtonProps>;
    "Group 83"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 15339882738"?: PrimitiveOverrideProps<ViewProps>;
    "ENGENHEIRO DE REDES"?: PrimitiveOverrideProps<TextProps>;
    "4,4"?: PrimitiveOverrideProps<TextProps>;
    "star_24dp_000000_FILL0_wght400_GRAD0_opsz24 139882741"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882742?: PrimitiveOverrideProps<IconProps>;
    "Aurora Tech"?: PrimitiveOverrideProps<TextProps>;
    "new_releases_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 139882744"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882745?: PrimitiveOverrideProps<IconProps>;
    "Group 80"?: PrimitiveOverrideProps<ViewProps>;
    "S\u00E3o Paulo - SP39882747"?: PrimitiveOverrideProps<TextProps>;
    "26 ago"?: PrimitiveOverrideProps<TextProps>;
    Presencial?: PrimitiveOverrideProps<TextProps>;
    Vector40701072?: PrimitiveOverrideProps<IconProps>;
    "Line 3539882751"?: PrimitiveOverrideProps<IconProps>;
    Button39882752?: PrimitiveOverrideProps<ButtonProps>;
    Button39882753?: PrimitiveOverrideProps<ButtonProps>;
    Button39882754?: PrimitiveOverrideProps<ButtonProps>;
    "Rectangle 20"?: PrimitiveOverrideProps<ViewProps>;
    Button41021207?: PrimitiveOverrideProps<ButtonProps>;
    Button41021208?: PrimitiveOverrideProps<ButtonProps>;
    Button41021209?: PrimitiveOverrideProps<ButtonProps>;
    "Group 397"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 152"?: PrimitiveOverrideProps<ViewProps>;
    "arrow_left_alt_24dp_5F6368_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882758?: PrimitiveOverrideProps<IconProps>;
    Empresa39882759?: PrimitiveOverrideProps<TextProps>;
    "1.783 avalia\u00E7\u00F5es"?: PrimitiveOverrideProps<TextProps>;
    "S\u00E3o Paulo - SP39882761"?: PrimitiveOverrideProps<TextProps>;
    "R$ 5.200,00"?: PrimitiveOverrideProps<TextProps>;
    "H\u00EDbrido39882763"?: PrimitiveOverrideProps<TextProps>;
    Hoje?: PrimitiveOverrideProps<TextProps>;
    "ANALISTA DE DADOS"?: PrimitiveOverrideProps<TextProps>;
    "image 7"?: PrimitiveOverrideProps<ImageProps>;
    "4,539882767"?: PrimitiveOverrideProps<TextProps>;
    "star_24dp_000000_FILL0_wght400_GRAD0_opsz24 139882768"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882769?: PrimitiveOverrideProps<IconProps>;
    "REKTR TEC"?: PrimitiveOverrideProps<TextProps>;
    "new_releases_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 139882771"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882772?: PrimitiveOverrideProps<IconProps>;
    Vector39882773?: PrimitiveOverrideProps<IconProps>;
    Button39882774?: PrimitiveOverrideProps<ButtonProps>;
    "Ellipse 106"?: PrimitiveOverrideProps<IconProps>;
    Vector39882776?: PrimitiveOverrideProps<IconProps>;
    "Line 33"?: PrimitiveOverrideProps<IconProps>;
    Vaga?: PrimitiveOverrideProps<TextProps>;
    "Valora\u00E7\u00F5es de funcion\u00E1rios da Rektr Tec"?: PrimitiveOverrideProps<TextProps>;
    "Valora\u00E7\u00F5es"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 157"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 159"?: PrimitiveOverrideProps<ViewProps>;
    "Avalia\u00E7\u00E3o geral da empresa"?: PrimitiveOverrideProps<TextProps>;
    "4,539882784"?: PrimitiveOverrideProps<TextProps>;
    "92%"?: PrimitiveOverrideProps<TextProps>;
    "89%"?: PrimitiveOverrideProps<TextProps>;
    "Recomendaria a um amigo"?: PrimitiveOverrideProps<TextProps>;
    "Aprovam a diretoria"?: PrimitiveOverrideProps<TextProps>;
    "Line 36"?: PrimitiveOverrideProps<IconProps>;
    "Line 37"?: PrimitiveOverrideProps<IconProps>;
    "star_24dp_000000_FILL0_wght400_GRAD0_opsz24 239882791"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882792?: PrimitiveOverrideProps<IconProps>;
    "Group 394"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 19"?: PrimitiveOverrideProps<ViewProps>;
    "image-removebg-preview (4) 4"?: PrimitiveOverrideProps<ImageProps>;
    "Group 430"?: PrimitiveOverrideProps<ViewProps>;
    Vector41051338?: PrimitiveOverrideProps<IconProps>;
    Ajuda?: PrimitiveOverrideProps<TextProps>;
    Vector41051340?: PrimitiveOverrideProps<IconProps>;
    Vector41051341?: PrimitiveOverrideProps<IconProps>;
    Vector41051342?: PrimitiveOverrideProps<IconProps>;
    "Jo\u00E3o Pedro Borges"?: PrimitiveOverrideProps<TextProps>;
    "AvatarPerfil 1"?: PrimitiveOverrideProps<ImageProps>;
} & EscapeHatchProps;
export declare type Vagas4Props = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: Vagas4OverridesProps | undefined | null;
}>;
export default function Vagas4(props: Vagas4Props): React.ReactElement;
