/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { ButtonProps, IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type Vagas6OverridesProps = {
    "1"?: PrimitiveOverrideProps<TextProps>;
    "2"?: PrimitiveOverrideProps<TextProps>;
    "3"?: PrimitiveOverrideProps<TextProps>;
    "4"?: PrimitiveOverrideProps<TextProps>;
    "5"?: PrimitiveOverrideProps<TextProps>;
    "6"?: PrimitiveOverrideProps<TextProps>;
    "7"?: PrimitiveOverrideProps<TextProps>;
    "8"?: PrimitiveOverrideProps<TextProps>;
    "9"?: PrimitiveOverrideProps<TextProps>;
    "10"?: PrimitiveOverrideProps<TextProps>;
    "11"?: PrimitiveOverrideProps<TextProps>;
    "12"?: PrimitiveOverrideProps<TextProps>;
    "13"?: PrimitiveOverrideProps<TextProps>;
    "14"?: PrimitiveOverrideProps<TextProps>;
    "15"?: PrimitiveOverrideProps<TextProps>;
    "16"?: PrimitiveOverrideProps<TextProps>;
    "17"?: PrimitiveOverrideProps<TextProps>;
    "18"?: PrimitiveOverrideProps<TextProps>;
    "19"?: PrimitiveOverrideProps<TextProps>;
    "20"?: PrimitiveOverrideProps<TextProps>;
    "21"?: PrimitiveOverrideProps<TextProps>;
    "22"?: PrimitiveOverrideProps<TextProps>;
    "23"?: PrimitiveOverrideProps<TextProps>;
    "24"?: PrimitiveOverrideProps<TextProps>;
    "25"?: PrimitiveOverrideProps<TextProps>;
    "26"?: PrimitiveOverrideProps<TextProps>;
    "27"?: PrimitiveOverrideProps<TextProps>;
    "28"?: PrimitiveOverrideProps<TextProps>;
    "29"?: PrimitiveOverrideProps<TextProps>;
    "30"?: PrimitiveOverrideProps<TextProps>;
    Vagas6?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 27"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 26"?: PrimitiveOverrideProps<ViewProps>;
    "Noise & Texture"?: PrimitiveOverrideProps<ImageProps>;
    "DALL\u00B7E 2024-11-02 01.57.03 - A softer abstract background with a pattern of faceted polygons in calming colors such as soft blues, greens, purples, and muted yellows. The shapes s 1"?: PrimitiveOverrideProps<ImageProps>;
    "Group 399"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 152"?: PrimitiveOverrideProps<ViewProps>;
    "1.783 avalia\u00E7\u00F5es"?: PrimitiveOverrideProps<TextProps>;
    "S\u00E3o Paulo - SP39886404"?: PrimitiveOverrideProps<TextProps>;
    "R$ 5.200,00"?: PrimitiveOverrideProps<TextProps>;
    "H\u00EDbrido39886406"?: PrimitiveOverrideProps<TextProps>;
    Hoje?: PrimitiveOverrideProps<TextProps>;
    "ANALISTA DE DADOS"?: PrimitiveOverrideProps<TextProps>;
    "image 7"?: PrimitiveOverrideProps<ImageProps>;
    "4,5"?: PrimitiveOverrideProps<TextProps>;
    "star_24dp_000000_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector41401475?: PrimitiveOverrideProps<IconProps>;
    "REKTR TEC"?: PrimitiveOverrideProps<TextProps>;
    "new_releases_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector41401484?: PrimitiveOverrideProps<IconProps>;
    Vector41401466?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 156"?: PrimitiveOverrideProps<ViewProps>;
    "Quero me Candidatar"?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 106"?: PrimitiveOverrideProps<IconProps>;
    Share?: PrimitiveOverrideProps<ImageProps>;
    "Line 33"?: PrimitiveOverrideProps<IconProps>;
    Vaga?: PrimitiveOverrideProps<TextProps>;
    Empresa?: PrimitiveOverrideProps<TextProps>;
    "-Descri\u00E7\u00E3o: Uma empresa busca um Analista de Dados para integrar sua equipe de tecnologia e inova\u00E7\u00E3o. O profissional ser\u00E1 respons\u00E1vel por coletar, organizar e analisar grandes volumes de dados, fornecendo insights valiosos para a tomada de decis\u00F5es estrat\u00E9gicas. Entre as principais responsabilidades est\u00E3o a cria\u00E7\u00E3o de relat\u00F3rios, identifica\u00E7\u00E3o de padr\u00F5es e tend\u00EAncias, e o desenvolvimento de solu\u00E7\u00F5es para otimizar processos internos. O Analista de Dados trabalhar\u00E1 em colabora\u00E7\u00E3o com diferentes departamentos, como marketing, vendas e opera\u00E7\u00F5es, para garantir que as decis\u00F5es baseadas em dados sejam precisas e eficazes. -Requisitos: Gradua\u00E7\u00E3o em Ci\u00EAncia de Dados, Engenharia, Estat\u00EDstica, TI ou \u00E1reas relacionadas; Experi\u00EAncia em an\u00E1lise de dados e utiliza\u00E7\u00E3o de ferramentas como Excel, SQL, Python, R ou Power BI;"?: PrimitiveOverrideProps<TextProps>;
    "Valora\u00E7\u00F5es"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 157"?: PrimitiveOverrideProps<ViewProps>;
    "Group 396"?: PrimitiveOverrideProps<ViewProps>;
    "Outras vagas semelhantes"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 15339886427"?: PrimitiveOverrideProps<ViewProps>;
    "DESIGN GR\u00C1FICO"?: PrimitiveOverrideProps<TextProps>;
    "4,1"?: PrimitiveOverrideProps<TextProps>;
    Star39886430?: PrimitiveOverrideProps<ImageProps>;
    "New Berg"?: PrimitiveOverrideProps<TextProps>;
    "Verified Account39886432"?: PrimitiveOverrideProps<ImageProps>;
    "S\u00E3o Paulo - SP39886433"?: PrimitiveOverrideProps<TextProps>;
    "09 out"?: PrimitiveOverrideProps<TextProps>;
    Remoto?: PrimitiveOverrideProps<TextProps>;
    Company39886436?: PrimitiveOverrideProps<ImageProps>;
    "Line 3539886437"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 15839886438"?: PrimitiveOverrideProps<ViewProps>;
    "Saiba mais39886439"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 15339886440"?: PrimitiveOverrideProps<ViewProps>;
    "SEGURAN\u00C7A DA INFORMA\u00C7\u00C3O"?: PrimitiveOverrideProps<TextProps>;
    "4,9"?: PrimitiveOverrideProps<TextProps>;
    Star39886443?: PrimitiveOverrideProps<ImageProps>;
    "City Corp"?: PrimitiveOverrideProps<TextProps>;
    "Verified Account39886445"?: PrimitiveOverrideProps<ImageProps>;
    "S\u00E3o Paulo - SP39886446"?: PrimitiveOverrideProps<TextProps>;
    "01 set"?: PrimitiveOverrideProps<TextProps>;
    "H\u00EDbrido39886448"?: PrimitiveOverrideProps<TextProps>;
    Company39886449?: PrimitiveOverrideProps<ImageProps>;
    "Line 3539886450"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 15839886451"?: PrimitiveOverrideProps<ViewProps>;
    "Saiba mais39886452"?: PrimitiveOverrideProps<TextProps>;
    "Group 83"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 15339886454"?: PrimitiveOverrideProps<ViewProps>;
    "ENGENHEIRO DE REDES"?: PrimitiveOverrideProps<TextProps>;
    "4,4"?: PrimitiveOverrideProps<TextProps>;
    Star39886457?: PrimitiveOverrideProps<ImageProps>;
    "Aurora Tech"?: PrimitiveOverrideProps<TextProps>;
    "Verified Account39886459"?: PrimitiveOverrideProps<ImageProps>;
    "Group 80"?: PrimitiveOverrideProps<ViewProps>;
    "S\u00E3o Paulo - SP39886461"?: PrimitiveOverrideProps<TextProps>;
    "26 ago"?: PrimitiveOverrideProps<TextProps>;
    Presencial?: PrimitiveOverrideProps<TextProps>;
    Company39886464?: PrimitiveOverrideProps<ImageProps>;
    "Line 3539886465"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 15839886466"?: PrimitiveOverrideProps<ViewProps>;
    "Saiba mais39886467"?: PrimitiveOverrideProps<TextProps>;
    "Group 394"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 19"?: PrimitiveOverrideProps<ViewProps>;
    "image-removebg-preview (4) 4"?: PrimitiveOverrideProps<ImageProps>;
    "Group 430"?: PrimitiveOverrideProps<ViewProps>;
    Vector41051324?: PrimitiveOverrideProps<IconProps>;
    Ajuda?: PrimitiveOverrideProps<TextProps>;
    Vector41051326?: PrimitiveOverrideProps<IconProps>;
    Vector41051327?: PrimitiveOverrideProps<IconProps>;
    Vector41051328?: PrimitiveOverrideProps<IconProps>;
    "Jo\u00E3o Pedro Borges"?: PrimitiveOverrideProps<TextProps>;
    Left?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 196"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 198"?: PrimitiveOverrideProps<ViewProps>;
    "Line 56"?: PrimitiveOverrideProps<IconProps>;
    "Line 57"?: PrimitiveOverrideProps<IconProps>;
    "Line 65"?: PrimitiveOverrideProps<IconProps>;
    "Line 58"?: PrimitiveOverrideProps<IconProps>;
    "Line 59"?: PrimitiveOverrideProps<IconProps>;
    "Line 60"?: PrimitiveOverrideProps<IconProps>;
    "Line 61"?: PrimitiveOverrideProps<IconProps>;
    "Line 62"?: PrimitiveOverrideProps<IconProps>;
    "Line 63"?: PrimitiveOverrideProps<IconProps>;
    "Hor\u00E1rios"?: PrimitiveOverrideProps<TextProps>;
    "09:00"?: PrimitiveOverrideProps<TextProps>;
    "11:00"?: PrimitiveOverrideProps<TextProps>;
    "09:45"?: PrimitiveOverrideProps<TextProps>;
    "11:45"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 199"?: PrimitiveOverrideProps<ViewProps>;
    "10:30"?: PrimitiveOverrideProps<TextProps>;
    "13:00"?: PrimitiveOverrideProps<TextProps>;
    AGENDAMENTO?: PrimitiveOverrideProps<TextProps>;
    "event_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39886501?: PrimitiveOverrideProps<IconProps>;
    "event_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 2"?: PrimitiveOverrideProps<ViewProps>;
    Vector39886503?: PrimitiveOverrideProps<IconProps>;
    "Novembro 2024"?: PrimitiveOverrideProps<TextProps>;
    "chevron_right_24dp_E8EAED_FILL0_wght400_GRAD0_opsz24 3"?: PrimitiveOverrideProps<ViewProps>;
    Vector39886506?: PrimitiveOverrideProps<IconProps>;
    "chevron_right_24dp_E8EAED_FILL0_wght400_GRAD0_opsz24 4"?: PrimitiveOverrideProps<ViewProps>;
    Vector39886508?: PrimitiveOverrideProps<IconProps>;
    DOM?: PrimitiveOverrideProps<TextProps>;
    SEG?: PrimitiveOverrideProps<TextProps>;
    TER?: PrimitiveOverrideProps<TextProps>;
    QUA?: PrimitiveOverrideProps<TextProps>;
    QUI?: PrimitiveOverrideProps<TextProps>;
    SEX?: PrimitiveOverrideProps<TextProps>;
    "S\u00C1B"?: PrimitiveOverrideProps<TextProps>;
    "Line 66"?: PrimitiveOverrideProps<IconProps>;
    "Line 67"?: PrimitiveOverrideProps<IconProps>;
    "Line 69"?: PrimitiveOverrideProps<IconProps>;
    "Line 68"?: PrimitiveOverrideProps<IconProps>;
    "Line 70"?: PrimitiveOverrideProps<IconProps>;
    "Fuso Hor\u00E1rio"?: PrimitiveOverrideProps<TextProps>;
    "Hor\u00E1rio de Bras\u00EDlia (19:50)"?: PrimitiveOverrideProps<TextProps>;
    "undraw_schedule_re_2vro 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39886553?: PrimitiveOverrideProps<IconProps>;
    Vector39886554?: PrimitiveOverrideProps<IconProps>;
    Vector39886555?: PrimitiveOverrideProps<IconProps>;
    Vector39886556?: PrimitiveOverrideProps<IconProps>;
    Vector39886557?: PrimitiveOverrideProps<IconProps>;
    Vector39886558?: PrimitiveOverrideProps<IconProps>;
    Vector39886559?: PrimitiveOverrideProps<IconProps>;
    Vector39886560?: PrimitiveOverrideProps<IconProps>;
    Vector39886561?: PrimitiveOverrideProps<IconProps>;
    Vector39886562?: PrimitiveOverrideProps<IconProps>;
    Vector39886563?: PrimitiveOverrideProps<IconProps>;
    Vector39886564?: PrimitiveOverrideProps<IconProps>;
    Vector39886565?: PrimitiveOverrideProps<IconProps>;
    Vector39886566?: PrimitiveOverrideProps<IconProps>;
    Vector39886567?: PrimitiveOverrideProps<IconProps>;
    Vector39886568?: PrimitiveOverrideProps<IconProps>;
    Vector39886569?: PrimitiveOverrideProps<IconProps>;
    Vector39886570?: PrimitiveOverrideProps<IconProps>;
    Vector39886571?: PrimitiveOverrideProps<IconProps>;
    Vector39886572?: PrimitiveOverrideProps<IconProps>;
    Vector39886573?: PrimitiveOverrideProps<IconProps>;
    Vector39886574?: PrimitiveOverrideProps<IconProps>;
    Vector39886575?: PrimitiveOverrideProps<IconProps>;
    Vector39886576?: PrimitiveOverrideProps<IconProps>;
    Vector39886577?: PrimitiveOverrideProps<IconProps>;
    Vector39886578?: PrimitiveOverrideProps<IconProps>;
    Vector39886579?: PrimitiveOverrideProps<IconProps>;
    Vector39886580?: PrimitiveOverrideProps<IconProps>;
    Vector39886581?: PrimitiveOverrideProps<IconProps>;
    Vector39886582?: PrimitiveOverrideProps<IconProps>;
    Vector39886583?: PrimitiveOverrideProps<IconProps>;
    Vector39886584?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 107"?: PrimitiveOverrideProps<IconProps>;
    "Data: 28/11/2024 - QUI"?: PrimitiveOverrideProps<TextProps>;
    "Hor\u00E1rio: 10:30 AM"?: PrimitiveOverrideProps<TextProps>;
    Button39886589?: PrimitiveOverrideProps<ButtonProps>;
    "update_24dp_5F6368_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39886591?: PrimitiveOverrideProps<IconProps>;
    "AvatarPerfil 1"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 24"?: PrimitiveOverrideProps<ViewProps>;
    Button41021221?: PrimitiveOverrideProps<ButtonProps>;
    Button41021222?: PrimitiveOverrideProps<ButtonProps>;
    Button41021223?: PrimitiveOverrideProps<ButtonProps>;
} & EscapeHatchProps;
export declare type Vagas6Props = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: Vagas6OverridesProps | undefined | null;
}>;
export default function Vagas6(props: Vagas6Props): React.ReactElement;
