/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { BancoImagens } from "../models";
import { ButtonProps, IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type Vagas5OverridesProps = {
    "1"?: PrimitiveOverrideProps<TextProps>;
    "2"?: PrimitiveOverrideProps<TextProps>;
    "3"?: PrimitiveOverrideProps<TextProps>;
    "4"?: PrimitiveOverrideProps<TextProps>;
    "5"?: PrimitiveOverrideProps<TextProps>;
    "6"?: PrimitiveOverrideProps<TextProps>;
    "7"?: PrimitiveOverrideProps<TextProps>;
    "8"?: PrimitiveOverrideProps<TextProps>;
    "9"?: PrimitiveOverrideProps<TextProps>;
    "10"?: PrimitiveOverrideProps<TextProps>;
    "11"?: PrimitiveOverrideProps<TextProps>;
    "12"?: PrimitiveOverrideProps<TextProps>;
    "13"?: PrimitiveOverrideProps<TextProps>;
    "14"?: PrimitiveOverrideProps<TextProps>;
    "15"?: PrimitiveOverrideProps<TextProps>;
    "16"?: PrimitiveOverrideProps<TextProps>;
    "17"?: PrimitiveOverrideProps<TextProps>;
    "18"?: PrimitiveOverrideProps<TextProps>;
    "19"?: PrimitiveOverrideProps<TextProps>;
    "20"?: PrimitiveOverrideProps<TextProps>;
    "21"?: PrimitiveOverrideProps<TextProps>;
    "22"?: PrimitiveOverrideProps<TextProps>;
    "23"?: PrimitiveOverrideProps<TextProps>;
    "24"?: PrimitiveOverrideProps<TextProps>;
    "25"?: PrimitiveOverrideProps<TextProps>;
    "26"?: PrimitiveOverrideProps<TextProps>;
    "27"?: PrimitiveOverrideProps<TextProps>;
    "28"?: PrimitiveOverrideProps<TextProps>;
    "29"?: PrimitiveOverrideProps<TextProps>;
    "30"?: PrimitiveOverrideProps<TextProps>;
    Vagas5?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 27"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 26"?: PrimitiveOverrideProps<ViewProps>;
    "Noise & Texture"?: PrimitiveOverrideProps<ImageProps>;
    "DALL\u00B7E 2024-11-02 01.57.03 - A softer abstract background with a pattern of faceted polygons in calming colors such as soft blues, greens, purples, and muted yellows. The shapes s 1"?: PrimitiveOverrideProps<ImageProps>;
    "Group 399"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 152"?: PrimitiveOverrideProps<ViewProps>;
    "1.783 avalia\u00E7\u00F5es"?: PrimitiveOverrideProps<TextProps>;
    "S\u00E3o Paulo - SP39886208"?: PrimitiveOverrideProps<TextProps>;
    "R$ 5.200,00"?: PrimitiveOverrideProps<TextProps>;
    "H\u00EDbrido39886210"?: PrimitiveOverrideProps<TextProps>;
    Hoje?: PrimitiveOverrideProps<TextProps>;
    "ANALISTA DE DADOS"?: PrimitiveOverrideProps<TextProps>;
    "image 7"?: PrimitiveOverrideProps<ImageProps>;
    "4,5"?: PrimitiveOverrideProps<TextProps>;
    "star_24dp_000000_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector41401472?: PrimitiveOverrideProps<IconProps>;
    "REKTR TEC"?: PrimitiveOverrideProps<TextProps>;
    "new_releases_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector41401481?: PrimitiveOverrideProps<IconProps>;
    Vector41401464?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 156"?: PrimitiveOverrideProps<ViewProps>;
    "Quero me Candidatar"?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 106"?: PrimitiveOverrideProps<IconProps>;
    Share?: PrimitiveOverrideProps<ImageProps>;
    "Line 33"?: PrimitiveOverrideProps<IconProps>;
    Vaga?: PrimitiveOverrideProps<TextProps>;
    Empresa?: PrimitiveOverrideProps<TextProps>;
    "-Descri\u00E7\u00E3o: Uma empresa busca um Analista de Dados para integrar sua equipe de tecnologia e inova\u00E7\u00E3o. O profissional ser\u00E1 respons\u00E1vel por coletar, organizar e analisar grandes volumes de dados, fornecendo insights valiosos para a tomada de decis\u00F5es estrat\u00E9gicas. Entre as principais responsabilidades est\u00E3o a cria\u00E7\u00E3o de relat\u00F3rios, identifica\u00E7\u00E3o de padr\u00F5es e tend\u00EAncias, e o desenvolvimento de solu\u00E7\u00F5es para otimizar processos internos. O Analista de Dados trabalhar\u00E1 em colabora\u00E7\u00E3o com diferentes departamentos, como marketing, vendas e opera\u00E7\u00F5es, para garantir que as decis\u00F5es baseadas em dados sejam precisas e eficazes. -Requisitos: Gradua\u00E7\u00E3o em Ci\u00EAncia de Dados, Engenharia, Estat\u00EDstica, TI ou \u00E1reas relacionadas; Experi\u00EAncia em an\u00E1lise de dados e utiliza\u00E7\u00E3o de ferramentas como Excel, SQL, Python, R ou Power BI;"?: PrimitiveOverrideProps<TextProps>;
    "Valora\u00E7\u00F5es"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 157"?: PrimitiveOverrideProps<ViewProps>;
    "Group 396"?: PrimitiveOverrideProps<ViewProps>;
    "Outras vagas semelhantes"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 15339886231"?: PrimitiveOverrideProps<ViewProps>;
    "DESIGN GR\u00C1FICO"?: PrimitiveOverrideProps<TextProps>;
    "4,1"?: PrimitiveOverrideProps<TextProps>;
    Star39886234?: PrimitiveOverrideProps<ImageProps>;
    "New Berg"?: PrimitiveOverrideProps<TextProps>;
    "Verified Account39886236"?: PrimitiveOverrideProps<ImageProps>;
    "S\u00E3o Paulo - SP39886237"?: PrimitiveOverrideProps<TextProps>;
    "09 out"?: PrimitiveOverrideProps<TextProps>;
    Remoto?: PrimitiveOverrideProps<TextProps>;
    Company39886240?: PrimitiveOverrideProps<ImageProps>;
    "Line 3539886241"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 15839886242"?: PrimitiveOverrideProps<ViewProps>;
    "Saiba mais39886243"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 15339886244"?: PrimitiveOverrideProps<ViewProps>;
    "SEGURAN\u00C7A DA INFORMA\u00C7\u00C3O"?: PrimitiveOverrideProps<TextProps>;
    "4,9"?: PrimitiveOverrideProps<TextProps>;
    Star39886247?: PrimitiveOverrideProps<ImageProps>;
    "City Corp"?: PrimitiveOverrideProps<TextProps>;
    "Verified Account39886249"?: PrimitiveOverrideProps<ImageProps>;
    "S\u00E3o Paulo - SP39886250"?: PrimitiveOverrideProps<TextProps>;
    "01 set"?: PrimitiveOverrideProps<TextProps>;
    "H\u00EDbrido39886252"?: PrimitiveOverrideProps<TextProps>;
    Company39886253?: PrimitiveOverrideProps<ImageProps>;
    "Line 3539886254"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 15839886255"?: PrimitiveOverrideProps<ViewProps>;
    "Saiba mais39886256"?: PrimitiveOverrideProps<TextProps>;
    "Group 83"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 15339886258"?: PrimitiveOverrideProps<ViewProps>;
    "ENGENHEIRO DE REDES"?: PrimitiveOverrideProps<TextProps>;
    "4,4"?: PrimitiveOverrideProps<TextProps>;
    Star39886261?: PrimitiveOverrideProps<ImageProps>;
    "Aurora Tech"?: PrimitiveOverrideProps<TextProps>;
    "Verified Account39886263"?: PrimitiveOverrideProps<ImageProps>;
    "Group 80"?: PrimitiveOverrideProps<ViewProps>;
    "S\u00E3o 28aulo - SP"?: PrimitiveOverrideProps<TextProps>;
    "26 ago"?: PrimitiveOverrideProps<TextProps>;
    Presencial?: PrimitiveOverrideProps<TextProps>;
    Company39886268?: PrimitiveOverrideProps<ImageProps>;
    "Line 3539886269"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 15839886270"?: PrimitiveOverrideProps<ViewProps>;
    "Saiba mais39886271"?: PrimitiveOverrideProps<TextProps>;
    "Group 394"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 19"?: PrimitiveOverrideProps<ViewProps>;
    "image-removebg-preview (4) 4"?: PrimitiveOverrideProps<ImageProps>;
    "Group 430"?: PrimitiveOverrideProps<ViewProps>;
    Vector41051317?: PrimitiveOverrideProps<IconProps>;
    Ajuda?: PrimitiveOverrideProps<TextProps>;
    Vector41051319?: PrimitiveOverrideProps<IconProps>;
    Vector41051320?: PrimitiveOverrideProps<IconProps>;
    Vector41051321?: PrimitiveOverrideProps<IconProps>;
    "Jo\u00E3o Pedro Borges"?: PrimitiveOverrideProps<TextProps>;
    Left?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 196"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 198"?: PrimitiveOverrideProps<ViewProps>;
    "event_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39886286?: PrimitiveOverrideProps<IconProps>;
    "event_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 2"?: PrimitiveOverrideProps<ViewProps>;
    Vector39886288?: PrimitiveOverrideProps<IconProps>;
    "Line 56"?: PrimitiveOverrideProps<IconProps>;
    "Line 57"?: PrimitiveOverrideProps<IconProps>;
    "Line 65"?: PrimitiveOverrideProps<IconProps>;
    "Line 58"?: PrimitiveOverrideProps<IconProps>;
    "Line 59"?: PrimitiveOverrideProps<IconProps>;
    "Line 60"?: PrimitiveOverrideProps<IconProps>;
    "Line 61"?: PrimitiveOverrideProps<IconProps>;
    "Line 62"?: PrimitiveOverrideProps<IconProps>;
    "Line 63"?: PrimitiveOverrideProps<IconProps>;
    "Hor\u00E1rios"?: PrimitiveOverrideProps<TextProps>;
    "09:00"?: PrimitiveOverrideProps<TextProps>;
    "11:00"?: PrimitiveOverrideProps<TextProps>;
    "09:45"?: PrimitiveOverrideProps<TextProps>;
    "11:45"?: PrimitiveOverrideProps<TextProps>;
    "10:30"?: PrimitiveOverrideProps<TextProps>;
    "13:00"?: PrimitiveOverrideProps<TextProps>;
    AGENDAMENTO?: PrimitiveOverrideProps<TextProps>;
    "Novembro 2024"?: PrimitiveOverrideProps<TextProps>;
    "chevron_right_24dp_E8EAED_FILL0_wght400_GRAD0_opsz24 3"?: PrimitiveOverrideProps<ViewProps>;
    Vector39886310?: PrimitiveOverrideProps<IconProps>;
    "chevron_right_24dp_E8EAED_FILL0_wght400_GRAD0_opsz24 4"?: PrimitiveOverrideProps<ViewProps>;
    Vector39886312?: PrimitiveOverrideProps<IconProps>;
    DOM?: PrimitiveOverrideProps<TextProps>;
    SEG?: PrimitiveOverrideProps<TextProps>;
    TER?: PrimitiveOverrideProps<TextProps>;
    QUA?: PrimitiveOverrideProps<TextProps>;
    QUI?: PrimitiveOverrideProps<TextProps>;
    SEX?: PrimitiveOverrideProps<TextProps>;
    "S\u00C1B"?: PrimitiveOverrideProps<TextProps>;
    "Line 66"?: PrimitiveOverrideProps<IconProps>;
    "Line 67"?: PrimitiveOverrideProps<IconProps>;
    "Line 69"?: PrimitiveOverrideProps<IconProps>;
    "Line 68"?: PrimitiveOverrideProps<IconProps>;
    "Line 70"?: PrimitiveOverrideProps<IconProps>;
    "Fuso Hor\u00E1rio"?: PrimitiveOverrideProps<TextProps>;
    "Hor\u00E1rio de Bras\u00EDlia (19:50)"?: PrimitiveOverrideProps<TextProps>;
    "undraw_schedule_re_2vro 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39886357?: PrimitiveOverrideProps<IconProps>;
    Vector39886358?: PrimitiveOverrideProps<IconProps>;
    Vector39886359?: PrimitiveOverrideProps<IconProps>;
    Vector39886360?: PrimitiveOverrideProps<IconProps>;
    Vector39886361?: PrimitiveOverrideProps<IconProps>;
    Vector39886362?: PrimitiveOverrideProps<IconProps>;
    Vector39886363?: PrimitiveOverrideProps<IconProps>;
    Vector39886364?: PrimitiveOverrideProps<IconProps>;
    Vector39886365?: PrimitiveOverrideProps<IconProps>;
    Vector39886366?: PrimitiveOverrideProps<IconProps>;
    Vector39886367?: PrimitiveOverrideProps<IconProps>;
    Vector39886368?: PrimitiveOverrideProps<IconProps>;
    Vector39886369?: PrimitiveOverrideProps<IconProps>;
    Vector39886370?: PrimitiveOverrideProps<IconProps>;
    Vector39886371?: PrimitiveOverrideProps<IconProps>;
    Vector39886372?: PrimitiveOverrideProps<IconProps>;
    Vector39886373?: PrimitiveOverrideProps<IconProps>;
    Vector39886374?: PrimitiveOverrideProps<IconProps>;
    Vector39886375?: PrimitiveOverrideProps<IconProps>;
    Vector39886376?: PrimitiveOverrideProps<IconProps>;
    Vector39886377?: PrimitiveOverrideProps<IconProps>;
    Vector39886378?: PrimitiveOverrideProps<IconProps>;
    Vector39886379?: PrimitiveOverrideProps<IconProps>;
    Vector39886380?: PrimitiveOverrideProps<IconProps>;
    Vector39886381?: PrimitiveOverrideProps<IconProps>;
    Vector39886382?: PrimitiveOverrideProps<IconProps>;
    Vector39886383?: PrimitiveOverrideProps<IconProps>;
    Vector39886384?: PrimitiveOverrideProps<IconProps>;
    Vector39886385?: PrimitiveOverrideProps<IconProps>;
    Vector39886386?: PrimitiveOverrideProps<IconProps>;
    Vector39886387?: PrimitiveOverrideProps<IconProps>;
    Vector39886388?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 107"?: PrimitiveOverrideProps<IconProps>;
    "28/11/2024 - QUI"?: PrimitiveOverrideProps<TextProps>;
    Button39886392?: PrimitiveOverrideProps<ButtonProps>;
    "update_24dp_5F6368_FILL0_wght400_GRAD0_opsz24 2"?: PrimitiveOverrideProps<ViewProps>;
    Vector39886394?: PrimitiveOverrideProps<IconProps>;
    "AvatarPerfil 1"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 24"?: PrimitiveOverrideProps<ViewProps>;
    Button41021318?: PrimitiveOverrideProps<ButtonProps>;
    Button41021319?: PrimitiveOverrideProps<ButtonProps>;
    Button41021320?: PrimitiveOverrideProps<ButtonProps>;
} & EscapeHatchProps;
export declare type Vagas5Props = React.PropsWithChildren<Partial<ViewProps> & {
    bancoImagens?: BancoImagens;
} & {
    overrides?: Vagas5OverridesProps | undefined | null;
}>;
export default function Vagas5(props: Vagas5Props): React.ReactElement;
