/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { ButtonProps, IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type Vagas3OverridesProps = {
    Vagas3?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 27"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 26"?: PrimitiveOverrideProps<ViewProps>;
    "Noise & Texture"?: PrimitiveOverrideProps<ImageProps>;
    "DALL\u00B7E 2024-11-02 01.57.03 - A softer abstract background with a pattern of faceted polygons in calming colors such as soft blues, greens, purples, and muted yellows. The shapes s 1"?: PrimitiveOverrideProps<ImageProps>;
    "Group 396"?: PrimitiveOverrideProps<ViewProps>;
    "Outras vagas semelhantes"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 15339882590"?: PrimitiveOverrideProps<ViewProps>;
    "DESIGN GR\u00C1FICO"?: PrimitiveOverrideProps<TextProps>;
    "4,1"?: PrimitiveOverrideProps<TextProps>;
    "star_24dp_000000_FILL0_wght400_GRAD0_opsz24 139882593"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882594?: PrimitiveOverrideProps<IconProps>;
    "New Berg"?: PrimitiveOverrideProps<TextProps>;
    "new_releases_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 2"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882597?: PrimitiveOverrideProps<IconProps>;
    "S\u00E3o Paulo - SP39882598"?: PrimitiveOverrideProps<TextProps>;
    "09 out"?: PrimitiveOverrideProps<TextProps>;
    Remoto?: PrimitiveOverrideProps<TextProps>;
    Vector40711096?: PrimitiveOverrideProps<IconProps>;
    "source_environment_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 4"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882604?: PrimitiveOverrideProps<IconProps>;
    "apartment_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 2"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882606?: PrimitiveOverrideProps<IconProps>;
    "Line 3539882607"?: PrimitiveOverrideProps<IconProps>;
    Button39882608?: PrimitiveOverrideProps<ButtonProps>;
    Button39882609?: PrimitiveOverrideProps<ButtonProps>;
    Button39882610?: PrimitiveOverrideProps<ButtonProps>;
    "Rectangle 15339882611"?: PrimitiveOverrideProps<ViewProps>;
    "SEGURAN\u00C7A DA INFORMA\u00C7\u00C3O"?: PrimitiveOverrideProps<TextProps>;
    "4,9"?: PrimitiveOverrideProps<TextProps>;
    "star_24dp_000000_FILL0_wght400_GRAD0_opsz24 2"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882615?: PrimitiveOverrideProps<IconProps>;
    "City Corp"?: PrimitiveOverrideProps<TextProps>;
    "new_releases_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 139882617"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882618?: PrimitiveOverrideProps<IconProps>;
    "S\u00E3o Paulo - SP39882619"?: PrimitiveOverrideProps<TextProps>;
    "01 set"?: PrimitiveOverrideProps<TextProps>;
    "H\u00EDbrido39882621"?: PrimitiveOverrideProps<TextProps>;
    Vector40711086?: PrimitiveOverrideProps<IconProps>;
    "source_environment_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 139882624"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882625?: PrimitiveOverrideProps<IconProps>;
    "apartment_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 139882626"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882627?: PrimitiveOverrideProps<IconProps>;
    "Line 3539882628"?: PrimitiveOverrideProps<IconProps>;
    Button39882629?: PrimitiveOverrideProps<ButtonProps>;
    Button39882630?: PrimitiveOverrideProps<ButtonProps>;
    Button39882631?: PrimitiveOverrideProps<ButtonProps>;
    "Group 83"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 15339882633"?: PrimitiveOverrideProps<ViewProps>;
    "ENGENHEIRO DE REDES"?: PrimitiveOverrideProps<TextProps>;
    "4,4"?: PrimitiveOverrideProps<TextProps>;
    "star_24dp_000000_FILL0_wght400_GRAD0_opsz24 139882636"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882637?: PrimitiveOverrideProps<IconProps>;
    "Aurora Tech"?: PrimitiveOverrideProps<TextProps>;
    "new_releases_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 139882639"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882640?: PrimitiveOverrideProps<IconProps>;
    "Group 80"?: PrimitiveOverrideProps<ViewProps>;
    "S\u00E3o Paulo - SP39882642"?: PrimitiveOverrideProps<TextProps>;
    "26 ago"?: PrimitiveOverrideProps<TextProps>;
    Presencial?: PrimitiveOverrideProps<TextProps>;
    "source_environment_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 139882645"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882646?: PrimitiveOverrideProps<IconProps>;
    "apartment_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 139882647"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882648?: PrimitiveOverrideProps<IconProps>;
    "Line 3539882649"?: PrimitiveOverrideProps<IconProps>;
    Button39882650?: PrimitiveOverrideProps<ButtonProps>;
    Button39882651?: PrimitiveOverrideProps<ButtonProps>;
    Button39882652?: PrimitiveOverrideProps<ButtonProps>;
    Vector40711088?: PrimitiveOverrideProps<IconProps>;
    "Group 399"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 152"?: PrimitiveOverrideProps<ViewProps>;
    "arrow_left_alt_24dp_5F6368_FILL0_wght400_GRAD0_opsz24 1"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882657?: PrimitiveOverrideProps<IconProps>;
    "1.783 avalia\u00E7\u00F5es"?: PrimitiveOverrideProps<TextProps>;
    "S\u00E3o Paulo - SP39882659"?: PrimitiveOverrideProps<TextProps>;
    "R$ 5.200,00"?: PrimitiveOverrideProps<TextProps>;
    "H\u00EDbrido39882661"?: PrimitiveOverrideProps<TextProps>;
    Hoje?: PrimitiveOverrideProps<TextProps>;
    "ANALISTA DE DADOS"?: PrimitiveOverrideProps<TextProps>;
    "image 7"?: PrimitiveOverrideProps<ImageProps>;
    "4,5"?: PrimitiveOverrideProps<TextProps>;
    "star_24dp_000000_FILL0_wght400_GRAD0_opsz24 139882666"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882667?: PrimitiveOverrideProps<IconProps>;
    "REKTR TEC"?: PrimitiveOverrideProps<TextProps>;
    "new_releases_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 139882669"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882670?: PrimitiveOverrideProps<IconProps>;
    "source_environment_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24 2"?: PrimitiveOverrideProps<ViewProps>;
    Vector39882672?: PrimitiveOverrideProps<IconProps>;
    Button39882673?: PrimitiveOverrideProps<ButtonProps>;
    "Ellipse 106"?: PrimitiveOverrideProps<IconProps>;
    Vector39882675?: PrimitiveOverrideProps<IconProps>;
    "Line 33"?: PrimitiveOverrideProps<IconProps>;
    Vaga?: PrimitiveOverrideProps<TextProps>;
    Empresa?: PrimitiveOverrideProps<TextProps>;
    "A Rektr Tec \u00E9 uma empresa de tecnologia focada em solu\u00E7\u00F5es digitais inovadoras, combinando desenvolvimento de software, an\u00E1lise de dados e intelig\u00EAncia artificial. Com atua\u00E7\u00E3o em diversas ind\u00FAstrias, a empresa busca transformar neg\u00F3cios e pessoas atrav\u00E9s da tecnologia. Valorizando a criatividade e o aprendizado cont\u00EDnuo, a Rektr Tec oferece um ambiente de trabalho inclusivo e din\u00E2mico."?: PrimitiveOverrideProps<TextProps>;
    "Setor: T\u00E9cnologia e desenvolvimento"?: PrimitiveOverrideProps<TextProps>;
    "Funcion\u00E1rios: M\u00E9dia (abaixo de 300 funcion\u00E1rios)"?: PrimitiveOverrideProps<TextProps>;
    "Links:"?: PrimitiveOverrideProps<TextProps>;
    "Site Oficial"?: PrimitiveOverrideProps<TextProps>;
    "Valora\u00E7\u00F5es"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 157"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 20"?: PrimitiveOverrideProps<ViewProps>;
    Button41021193?: PrimitiveOverrideProps<ButtonProps>;
    Button41021194?: PrimitiveOverrideProps<ButtonProps>;
    Button41021195?: PrimitiveOverrideProps<ButtonProps>;
    "Group 394"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 19"?: PrimitiveOverrideProps<ViewProps>;
    "image-removebg-preview (4) 4"?: PrimitiveOverrideProps<ImageProps>;
    "Group 430"?: PrimitiveOverrideProps<ViewProps>;
    Vector41051303?: PrimitiveOverrideProps<IconProps>;
    Ajuda?: PrimitiveOverrideProps<TextProps>;
    Vector41051305?: PrimitiveOverrideProps<IconProps>;
    Vector41051306?: PrimitiveOverrideProps<IconProps>;
    Vector41051307?: PrimitiveOverrideProps<IconProps>;
    "Jo\u00E3o Pedro Borges"?: PrimitiveOverrideProps<TextProps>;
    "AvatarPerfil 1"?: PrimitiveOverrideProps<ImageProps>;
} & EscapeHatchProps;
export declare type Vagas3Props = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: Vagas3OverridesProps | undefined | null;
}>;
export default function Vagas3(props: Vagas3Props): React.ReactElement;
